/*GENERATED BY OBNC 0.16.1*/

#include <obnc/In.h>
#include <obnc/Out.h>
#include <obnc/Files.h>
#include "ORS.h"
#include "ORP.h"
#include <obnc/OBNC.h>

#define OBERON_SOURCE_FILENAME "Oberon.Mod"

static Files__File_ file_;

static char filename_[40];

#if OBNC_CONFIG_TARGET_EMB
int main(void)
{
	OBNC_Init(0, NULL);
#else
int main(int argc, char *argv[])
{
	OBNC_Init(argc, argv);
#endif
	In__Init();
	Out__Init();
	Files__Init();
	ORS__Init();
	ORP__Init();
	Out__String_("File to compile: ", 18);
	In__String_(filename_, 40);
	file_ = Files__Old_(filename_, 40);
	if (file_ == 0) {
		Out__String_("File not found.", 16);
		Out__Ln_();
	}
	else {
		ORS__Init_(file_, 0);
		ORP__Module_();
	}
	Files__Close_(file_);
	return 0;
}
