/*GENERATED BY OBNC 0.16.1*/

#include "ORG.h"
#include <obnc/Out.h>
#include <obnc/Files.h>
#include "ORS.h"
#include "ORB.h"
#include <obnc/OBNC.h>

#define OBERON_SOURCE_FILENAME "ORG.Mod"

const int ORG__Exit_id;
const int *const ORG__Exit_ids[1] = {&ORG__Exit_id};
const OBNC_Td ORG__Exit_td = {ORG__Exit_ids, 1};

const int ORG__Item_id;
const int *const ORG__Item_ids[1] = {&ORG__Item_id};
const OBNC_Td ORG__Item_td = {ORG__Item_ids, 1};

const int ORG__INSTRUCTION_id;
const int *const ORG__INSTRUCTION_ids[1] = {&ORG__INSTRUCTION_id};
const OBNC_Td ORG__INSTRUCTION_td = {ORG__INSTRUCTION_ids, 1};

const int ORG__SYSTEMCALLS_id;
const int *const ORG__SYSTEMCALLS_ids[1] = {&ORG__SYSTEMCALLS_id};
const OBNC_Td ORG__SYSTEMCALLS_td = {ORG__SYSTEMCALLS_ids, 1};

OBNC_INTEGER ORG__pc_, ORG__pcbytes_, ORG__varsize_;

static OBNC_INTEGER tdx_, strx_;

static OBNC_INTEGER entry_;

static OBNC_INTEGER frame_;

static OBNC_INTEGER fixorgP_, fixorgD_, fixorgT_;

static OBNC_INTEGER version_;

static ORG__INSTRUCTION_ code_[8000];

static OBNC_INTEGER data_[160];

static char str_[2400];

static void mm_(void)
{

	Out__String_("YYYYYYYYYYYYYYY", 16);
	Out__Ln_();
}


static void WINT_(OBNC_INTEGER x_)
{

	Out__Int_(x_, 3);
	Out__Ln_();
}


static void WSTR_(const char x_[], OBNC_INTEGER x_len)
{

	Out__String_(x_, x_len);
	Out__Ln_();
}


static void PUT0_(OBNC_INTEGER op_)
{

	Out__Int_(ORG__pc_, 6);
	code_[OBNC_IT(ORG__pc_, 8000, 282)].op_ = (unsigned char) op_;
	OBNC_INC(ORG__pcbytes_);
	OBNC_INC(ORG__pc_);
	if (op_ == 0) {
		Out__String_(" SYSCALL ", 10);
	}
	else if (op_ == 1) {
		Out__String_(" ADD     ", 10);
	}
	else if (op_ == 2) {
		Out__String_(" SUB     ", 10);
	}
	else if (op_ == 3) {
		Out__String_(" MUL     ", 10);
	}
	else if (op_ == 4) {
		Out__String_(" DIV     ", 10);
	}
	else if (op_ == 5) {
		Out__String_(" ABS     ", 10);
	}
	else if (op_ == 7) {
		Out__String_(" FADD    ", 10);
	}
	else if (op_ == 8) {
		Out__String_(" FSUB    ", 10);
	}
	else if (op_ == 9) {
		Out__String_(" FMUL    ", 10);
	}
	else if (op_ == 10) {
		Out__String_(" FDIV    ", 10);
	}
	else if (op_ == 11) {
		Out__String_(" FABS    ", 10);
	}
	else if (op_ == 13) {
		Out__String_(" MOD     ", 10);
	}
	else if (op_ == 6) {
		Out__String_(" NEG     ", 10);
	}
	else if (op_ == 12) {
		Out__String_(" FNEG    ", 10);
	}
	else if (op_ == 14) {
		Out__String_(" ODD     ", 10);
	}
	else if (op_ == 29) {
		Out__String_(" FLOOR   ", 10);
	}
	else if (op_ == 30) {
		Out__String_(" FLOAT   ", 10);
	}
	else if (op_ == 31) {
		Out__String_(" IN      ", 10);
	}
	else if (op_ == 32) {
		Out__String_(" NOT     ", 10);
	}
	else if (op_ == 33) {
		Out__String_(" LSL     ", 10);
	}
	else if (op_ == 34) {
		Out__String_(" ASR     ", 10);
	}
	else if (op_ == 35) {
		Out__String_(" LSR     ", 10);
	}
	else if (op_ == 36) {
		Out__String_(" ROR     ", 10);
	}
	else if (op_ == 37) {
		Out__String_(" AND     ", 10);
	}
	else if (op_ == 38) {
		Out__String_(" ANN     ", 10);
	}
	else if (op_ == 39) {
		Out__String_(" IOR     ", 10);
	}
	else if (op_ == 40) {
		Out__String_(" XOR     ", 10);
	}
	else if (op_ == 41) {
		Out__String_(" PUSH    ", 10);
	}
	else if (op_ == 42) {
		Out__String_(" POP1    ", 10);
	}
	else if (op_ == 43) {
		Out__String_(" POP2    ", 10);
	}
	else if (op_ == 45) {
		Out__String_(" AC1TO2  ", 10);
	}
	else if (op_ == 46) {
		Out__String_(" AC2TO1  ", 10);
	}
	else if (op_ == 47) {
		Out__String_(" LDACC1  ", 10);
	}
	else if (op_ == 48) {
		Out__String_(" LDACC2  ", 10);
	}
	else if (op_ == 49) {
		Out__String_(" STM     ", 10);
	}
	else if (op_ == 15) {
		Out__String_(" INC     ", 10);
	}
	else if (op_ == 16) {
		Out__String_(" INC2    ", 10);
	}
	else if (op_ == 17) {
		Out__String_(" INC4    ", 10);
	}
	else if (op_ == 18) {
		Out__String_(" INCP    ", 10);
	}
	else if (op_ == 19) {
		Out__String_(" INCP2   ", 10);
	}
	else if (op_ == 20) {
		Out__String_(" INCP4   ", 10);
	}
	else if (op_ == 21) {
		Out__String_(" DEC     ", 10);
	}
	else if (op_ == 22) {
		Out__String_(" DEC2    ", 10);
	}
	else if (op_ == 23) {
		Out__String_(" DEC4    ", 10);
	}
	else if (op_ == 24) {
		Out__String_(" DECP    ", 10);
	}
	else if (op_ == 44) {
		Out__String_(" LEAVE   ", 10);
	}
	else if (op_ == 25) {
		Out__String_(" DECP2   ", 10);
	}
	else if (op_ == 26) {
		Out__String_(" DECP4   ", 10);
	}
	else if (op_ == 27) {
		Out__String_(" ADDP    ", 10);
	}
	else if (op_ == 28) {
		Out__String_(" SUBP    ", 10);
	}
	else if (op_ == 50) {
		Out__String_(" INCLP   ", 10);
	}
	else if (op_ == 51) {
		Out__String_(" EXCLP   ", 10);
	}
	else if (op_ == 52) {
		Out__String_(" COPY    ", 10);
	}
	else if (op_ == 53) {
		Out__String_(" COPYW   ", 10);
	}
	else if (op_ == 54) {
		Out__String_(" EQ      ", 10);
	}
	else if (op_ == 55) {
		Out__String_(" NE      ", 10);
	}
	else if (op_ == 56) {
		Out__String_(" GT      ", 10);
	}
	else if (op_ == 57) {
		Out__String_(" LT      ", 10);
	}
	else if (op_ == 58) {
		Out__String_(" GE      ", 10);
	}
	else if (op_ == 59) {
		Out__String_(" LE      ", 10);
	}
	else if (op_ == 60) {
		Out__String_(" EQ0     ", 10);
	}
	else if (op_ == 61) {
		Out__String_(" NE0     ", 10);
	}
	else if (op_ == 62) {
		Out__String_(" GE0     ", 10);
	}
	else if (op_ == 63) {
		Out__String_(" GT0     ", 10);
	}
	else if (op_ == 64) {
		Out__String_(" LE0     ", 10);
	}
	else if (op_ == 65) {
		Out__String_(" LT0     ", 10);
	}
	else if (op_ == 66) {
		Out__String_(" FEQ     ", 10);
	}
	else if (op_ == 67) {
		Out__String_(" FNE     ", 10);
	}
	else if (op_ == 68) {
		Out__String_(" FGT     ", 10);
	}
	else if (op_ == 69) {
		Out__String_(" FLT     ", 10);
	}
	else if (op_ == 70) {
		Out__String_(" FGE     ", 10);
	}
	else if (op_ == 71) {
		Out__String_(" FLE     ", 10);
	}
	else if (op_ == 72) {
		Out__String_(" FEQ0    ", 10);
	}
	else if (op_ == 73) {
		Out__String_(" FNE0    ", 10);
	}
	else if (op_ == 74) {
		Out__String_(" FGE0    ", 10);
	}
	else if (op_ == 75) {
		Out__String_(" FGT0    ", 10);
	}
	else if (op_ == 76) {
		Out__String_(" FLE0    ", 10);
	}
	else if (op_ == 77) {
		Out__String_(" FLT0    ", 10);
	}
	else if (op_ == 78) {
		Out__String_(" SEQ     ", 10);
	}
	else if (op_ == 79) {
		Out__String_(" SNE     ", 10);
	}
	else if (op_ == 80) {
		Out__String_(" SLE     ", 10);
	}
	else if (op_ == 81) {
		Out__String_(" SLT     ", 10);
	}
	else if (op_ == 82) {
		Out__String_(" EQP     ", 10);
	}
	else if (op_ == 83) {
		Out__String_(" PUT     ", 10);
	}
	else if (op_ == 84) {
		Out__String_(" GET     ", 10);
	}
	else if (op_ == 85) {
		Out__String_(" BIT     ", 10);
	}
	Out__Ln_();
}


static void PUT1_(OBNC_INTEGER op_, OBNC_INTEGER ofs_)
{

	Out__Int_(ORG__pc_, 6);
	if (op_ <= 90) {
		OBNC_INC_N(ORG__pcbytes_, 5);
	}
	else if (op_ <= 95) {
		if (ofs_ < 256) {
			OBNC_INC_N(ORG__pcbytes_, 2);
		}
		else {
			op_ = op_ + 34;
			OBNC_INC_N(ORG__pcbytes_, 3);
		}
	}
	else {
		if ((-128 <= op_) && (op_ <= 127)) {
			OBNC_INC_N(ORG__pcbytes_, 2);
		}
		else {
			op_ = op_ + 34;
			OBNC_INC_N(ORG__pcbytes_, 3);
		}
	}
	code_[OBNC_IT(ORG__pc_, 8000, 389)].op_ = (unsigned char) op_;
	code_[OBNC_IT(ORG__pc_, 8000, 389)].a_ = ofs_;
	if (op_ == 87) {
		Out__String_(" PUSHC    ", 11);
	}
	else if (op_ == 88) {
		Out__String_(" LDC1     ", 11);
	}
	else if (op_ == 89) {
		Out__String_(" LDC2     ", 11);
	}
	else if (op_ == 92) {
		Out__String_(" PUSHLM   ", 11);
	}
	else if (op_ == 93) {
		Out__String_(" PUSHGM   ", 11);
	}
	else if (op_ == 94) {
		Out__String_(" ENTER    ", 11);
	}
	else if (op_ == 95) {
		Out__String_(" PUSHRET  ", 11);
	}
	else if (op_ == 96) {
		Out__String_(" JUMP     ", 11);
	}
	else if (op_ == 97) {
		Out__String_(" BEQ0     ", 11);
	}
	else if (op_ == 98) {
		Out__String_(" BNE0     ", 11);
	}
	else if (op_ == 99) {
		Out__String_(" BLT      ", 11);
	}
	else if (op_ == 126) {
		Out__String_(" PUSHLML  ", 11);
	}
	else if (op_ == 127) {
		Out__String_(" PUSHGML  ", 11);
	}
	else if (op_ == 128) {
		Out__String_(" ENTERL   ", 11);
	}
	else if (op_ == 129) {
		Out__String_(" PUSHRETL ", 11);
	}
	else if (op_ == 130) {
		Out__String_(" JUMPL    ", 11);
	}
	else if (op_ == 131) {
		Out__String_(" BEQ0L    ", 11);
	}
	else if (op_ == 132) {
		Out__String_(" BNE0L    ", 11);
	}
	else if (op_ == 133) {
		Out__String_(" BLTL     ", 11);
	}
	Out__Int_(ofs_, 2);
	Out__Ln_();
	OBNC_INC(ORG__pc_);
}


static void PUTCall_(OBNC_INTEGER mod_, OBNC_INTEGER ofs_)
{
	OBNC_INTEGER op_;

	Out__Int_(ORG__pc_, 6);
	if (mod_ >= 0) {
		if (ofs_ < 256) {
			op_ = 116;
			OBNC_INC_N(ORG__pcbytes_, 2);
			Out__String_(" CALL   ", 9);
		}
		else {
			op_ = 150;
			OBNC_INC_N(ORG__pcbytes_, 3);
			Out__String_(" CALLL  ", 9);
		}
		code_[OBNC_IT(ORG__pc_, 8000, 428)].a_ = ofs_;
	}
	else {
		if (ofs_ < 4096) {
			op_ = 117;
			OBNC_INC_N(ORG__pcbytes_, 3);
			code_[OBNC_IT(ORG__pc_, 8000, 432)].a_ = OBNC_LSL(-mod_, 12) + ofs_;
			Out__String_(" CALLEXT ", 10);
		}
		else {
			op_ = 151;
			OBNC_INC_N(ORG__pcbytes_, 4);
			code_[OBNC_IT(ORG__pc_, 8000, 436)].a_ = OBNC_LSL(-mod_, 20) + ofs_;
			Out__String_(" CALLEXTL ", 11);
		}
		Out__Int_((-mod_), 2);
	}
	Out__Int_(ofs_, 5);
	Out__Ln_();
	code_[OBNC_IT(ORG__pc_, 8000, 442)].op_ = (unsigned char) op_;
	OBNC_INC(ORG__pc_);
}


static void PUTTrap_(OBNC_INTEGER trapnum_, OBNC_INTEGER operand_)
{

	OBNC_INC_N(ORG__pcbytes_, 7);
	code_[OBNC_IT(ORG__pc_, 8000, 448)].op_ = (unsigned char) 86;
	Out__Int_(ORG__pc_, 6);
	Out__String_(" TRAP ", 7);
	Out__Int_(trapnum_, 6);
	if (trapnum_ == 1) {
		if (operand_ == -1) {
			operand_ = 8191;
		}
		else if (operand_ == -2) {
			operand_ = 8190;
		}
		code_[OBNC_IT(ORG__pc_, 8000, 455)].a_ = OBNC_LSL(trapnum_, 13) + operand_;
	}
	else {
		code_[OBNC_IT(ORG__pc_, 8000, 456)].a_ = OBNC_LSL(trapnum_, 13);
	}
	Out__Ln_();
	code_[OBNC_IT(ORG__pc_, 8000, 459)].b_ = ORS__Pos_();
	OBNC_INC(ORG__pc_);
}


static void PUTStoreM_(OBNC_INTEGER op_, OBNC_INTEGER cst_)
{

	Out__Int_(ORG__pc_, 6);
	if (op_ == 80) {
		op_ = 91;
		Out__String_(" STCBM ", 8);
		OBNC_INC_N(ORG__pcbytes_, 2);
	}
	else if (op_ == 79) {
		op_ = 90;
		Out__String_(" STCWM ", 8);
		OBNC_INC_N(ORG__pcbytes_, 5);
	}
	Out__Int_(cst_, 6);
	Out__Ln_();
	code_[OBNC_IT(ORG__pc_, 8000, 471)].op_ = (unsigned char) op_;
	code_[OBNC_IT(ORG__pc_, 8000, 471)].a_ = cst_;
	OBNC_INC(ORG__pc_);
}


static void OutLevel_(OBNC_INTEGER lev_)
{

	if (lev_ > 0) {
		Out__String_("LOC+", 5);
	}
	else {
		Out__String_("GLO+", 5);
	}
}


static void PUTStoreLong_(OBNC_INTEGER op_, OBNC_INTEGER cst_, OBNC_INTEGER level_, OBNC_INTEGER ofs_, OBNC_INTEGER acc_)
{

	Out__Int_(ORG__pc_, 6);
	if (acc_ == -1) {
		if (level_ > 0) {
			if (op_ == 79) {
				op_ = 158;
				Out__String_(" STLCWL ", 9);
				OBNC_INC_N(ORG__pcbytes_, 7);
			}
			else if (op_ == 80) {
				op_ = 156;
				Out__String_(" STLCBL ", 9);
				OBNC_INC_N(ORG__pcbytes_, 4);
			}
		}
		else if (level_ == 0) {
			if (op_ == 79) {
				op_ = 159;
				Out__String_(" STGCWL ", 9);
				OBNC_INC_N(ORG__pcbytes_, 7);
			}
			else if (op_ == 80) {
				op_ = 157;
				Out__String_(" STGCBL ", 9);
				OBNC_INC_N(ORG__pcbytes_, 4);
			}
		}
		code_[OBNC_IT(ORG__pc_, 8000, 493)].op_ = (unsigned char) op_;
		code_[OBNC_IT(ORG__pc_, 8000, 494)].a_ = cst_;
		code_[OBNC_IT(ORG__pc_, 8000, 494)].b_ = ofs_;
		Out__Int_(cst_, 6);
	}
	else {
		if (level_ > 0) {
			if (op_ == 79) {
				op_ = 134;
				Out__String_(" STLWL  ", 9);
			}
			else if (op_ == 80) {
				op_ = 135;
				Out__String_(" STLBL  ", 9);
			}
		}
		else if (level_ == 0) {
			if (op_ == 79) {
				op_ = 136;
				Out__String_(" STGWL  ", 9);
			}
			else if (op_ == 80) {
				op_ = 137;
				Out__String_(" STGBL  ", 9);
			}
		}
		OBNC_INC_N(ORG__pcbytes_, 3);
		code_[OBNC_IT(ORG__pc_, 8000, 507)].op_ = (unsigned char) op_;
		code_[OBNC_IT(ORG__pc_, 8000, 508)].a_ = ofs_;
	}
	Out__String_("   ", 4);
	OutLevel_(level_);
	Out__Int_(ofs_, 2);
	Out__Ln_();
	OBNC_INC(ORG__pc_);
}


static void PUTStore_(OBNC_INTEGER op_, OBNC_INTEGER cst_, OBNC_INTEGER level_, OBNC_INTEGER ofs_, OBNC_INTEGER acc_)
{

	if (ofs_ >= 256) {
		PUTStoreLong_(op_, cst_, level_, ofs_, acc_);
	}
	else {
		Out__Int_(ORG__pc_, 6);
		if (acc_ == -1) {
			if (level_ > 0) {
				if (op_ == 79) {
					op_ = 124;
					Out__String_(" STLCW  ", 9);
					OBNC_INC_N(ORG__pcbytes_, 6);
				}
				else if (op_ == 80) {
					op_ = 122;
					Out__String_(" STLCB  ", 9);
					OBNC_INC_N(ORG__pcbytes_, 3);
				}
			}
			else if (level_ == 0) {
				if (op_ == 79) {
					op_ = 125;
					Out__String_(" STGCW  ", 9);
					OBNC_INC_N(ORG__pcbytes_, 6);
				}
				else if (op_ == 80) {
					op_ = 123;
					Out__String_(" STGCB  ", 9);
					OBNC_INC_N(ORG__pcbytes_, 3);
				}
			}
			code_[OBNC_IT(ORG__pc_, 8000, 529)].op_ = (unsigned char) op_;
			code_[OBNC_IT(ORG__pc_, 8000, 530)].a_ = cst_;
			code_[OBNC_IT(ORG__pc_, 8000, 530)].b_ = ofs_;
			Out__Int_(cst_, 6);
		}
		else {
			if (level_ > 0) {
				if (op_ == 79) {
					op_ = 100;
					Out__String_(" STLW   ", 9);
				}
				else if (op_ == 80) {
					op_ = 101;
					Out__String_(" STLB   ", 9);
				}
			}
			else if (level_ == 0) {
				if (op_ == 79) {
					op_ = 102;
					Out__String_(" STGW   ", 9);
				}
				else if (op_ == 80) {
					op_ = 103;
					Out__String_(" STGB   ", 9);
				}
			}
			OBNC_INC_N(ORG__pcbytes_, 2);
			code_[OBNC_IT(ORG__pc_, 8000, 543)].op_ = (unsigned char) op_;
			code_[OBNC_IT(ORG__pc_, 8000, 544)].a_ = ofs_;
		}
		Out__String_("   ", 4);
		OutLevel_(level_);
		Out__Int_(ofs_, 2);
		Out__Ln_();
		OBNC_INC(ORG__pc_);
	}
}


void ORG__PUTLoadExtLong_(OBNC_INTEGER op_, OBNC_INTEGER modnmb_, OBNC_INTEGER ofs_, OBNC_INTEGER acc_)
{

	Out__Int_(ORG__pc_, 6);
	OBNC_INC_N(ORG__pcbytes_, 4);
	if (acc_ == 1) {
		if (op_ == 77) {
			op_ = 152;
		}
		else {
			op_ = 154;
		}
	}
	else {
		if (op_ == 77) {
			op_ = 153;
		}
		else {
			op_ = 155;
		}
	}
	code_[OBNC_IT(ORG__pc_, 8000, 561)].op_ = (unsigned char) op_;
	code_[OBNC_IT(ORG__pc_, 8000, 562)].a_ = OBNC_LSL(modnmb_, 20) + ofs_;
	if (op_ == 152) {
		Out__String_(" LDWEXT1L ", 11);
	}
	else if (op_ == 154) {
		Out__String_(" LDMEXT1L ", 11);
	}
	else if (op_ == 153) {
		Out__String_(" LDWEXT2L ", 11);
	}
	else if (op_ == 155) {
		Out__String_(" LDMEXT2L ", 11);
	}
	Out__Int_(modnmb_, 3);
	Out__Int_(ofs_, 3);
	Out__Ln_();
	OBNC_INC(ORG__pc_);
}


void ORG__PUTLoadExt_(OBNC_INTEGER op_, OBNC_INTEGER modnmb_, OBNC_INTEGER ofs_, OBNC_INTEGER acc_)
{

	if (ofs_ >= 4096) {
		ORG__PUTLoadExtLong_(op_, modnmb_, ofs_, acc_);
	}
	else {
		Out__Int_(ORG__pc_, 6);
		OBNC_INC_N(ORG__pcbytes_, 3);
		if (acc_ == 1) {
			if (op_ == 77) {
				op_ = 118;
			}
			else {
				op_ = 120;
			}
		}
		else {
			if (op_ == 77) {
				op_ = 119;
			}
			else {
				op_ = 121;
			}
		}
		code_[OBNC_IT(ORG__pc_, 8000, 585)].op_ = (unsigned char) op_;
		code_[OBNC_IT(ORG__pc_, 8000, 586)].a_ = OBNC_LSL(modnmb_, 12) + ofs_;
		if (op_ == 118) {
			Out__String_(" LDWEXT1 ", 10);
		}
		else if (op_ == 120) {
			Out__String_(" LDMEXT1 ", 10);
		}
		else if (op_ == 119) {
			Out__String_(" LDWEXT2 ", 10);
		}
		else if (op_ == 121) {
			Out__String_(" LDMEXT2 ", 10);
		}
		Out__Int_(modnmb_, 3);
		Out__Int_(ofs_, 3);
		Out__Ln_();
		OBNC_INC(ORG__pc_);
	}
}


static void PUTLoadLong_(OBNC_INTEGER op_, OBNC_INTEGER level_, OBNC_INTEGER ofs_, OBNC_INTEGER acc_)
{

	Out__Int_(ORG__pc_, 6);
	if (op_ == 81) {
		if (level_ == 0) {
			if (acc_ == 1) {
				op_ = 140;
				Out__String_(" LDGM1L ", 9);
			}
			else if (acc_ == 2) {
				op_ = 141;
				Out__String_(" LDGM2L ", 9);
			}
		}
		else {
			if (acc_ == 1) {
				op_ = 138;
				Out__String_(" LDLM1L ", 9);
			}
			else if (acc_ == 2) {
				op_ = 139;
				Out__String_(" LDLM2L ", 9);
			}
		}
		Out__String_("   ", 4);
		OutLevel_(level_);
		Out__Int_(ofs_, 2);
	}
	else {
		if (level_ == 0) {
			if (acc_ == 1) {
				if (op_ == 77) {
					op_ = 142;
					Out__String_(" LDGW1L ", 9);
				}
				else if (op_ == 78) {
					op_ = 144;
					Out__String_(" LDGB1L ", 9);
				}
			}
			else {
				if (op_ == 77) {
					op_ = 143;
					Out__String_(" LDGW2L ", 9);
				}
				else if (op_ == 78) {
					op_ = 145;
					Out__String_(" LDGB2L ", 9);
				}
			}
		}
		else {
			if (acc_ == 1) {
				if (op_ == 77) {
					op_ = 146;
					Out__String_(" LDLW1L ", 9);
				}
				else if (op_ == 78) {
					op_ = 148;
					Out__String_(" LDLB1L ", 9);
				}
			}
			else {
				if (op_ == 77) {
					op_ = 147;
					Out__String_(" LDLW2L ", 9);
				}
				else if (op_ == 78) {
					op_ = 149;
					Out__String_(" LDLB2L ", 9);
				}
			}
		}
		Out__String_("   [", 5);
		OutLevel_(level_);
		Out__Int_(ofs_, 2);
		Out__String_("]", 2);
	}
	OBNC_INC_N(ORG__pcbytes_, 3);
	code_[OBNC_IT(ORG__pc_, 8000, 637)].op_ = (unsigned char) op_;
	code_[OBNC_IT(ORG__pc_, 8000, 638)].a_ = ofs_;
	OBNC_INC(ORG__pc_);
	Out__Ln_();
}


static void PUTLoad_(OBNC_INTEGER op_, OBNC_INTEGER level_, OBNC_INTEGER ofs_, OBNC_INTEGER acc_)
{

	if (level_ < 0) {
		ORG__PUTLoadExt_(op_, (-level_), ofs_, acc_);
	}
	else {
		if (ofs_ >= 256) {
			PUTLoadLong_(op_, level_, ofs_, acc_);
		}
		else {
			Out__Int_(ORG__pc_, 6);
			if (op_ == 81) {
				if (level_ == 0) {
					if (acc_ == 1) {
						op_ = 106;
						Out__String_(" LDGM1  ", 9);
					}
					else if (acc_ == 2) {
						op_ = 107;
						Out__String_(" LDGM2  ", 9);
					}
				}
				else {
					if (acc_ == 1) {
						op_ = 104;
						Out__String_(" LDLM1  ", 9);
					}
					else if (acc_ == 2) {
						op_ = 105;
						Out__String_(" LDLM2  ", 9);
					}
				}
				Out__String_("   ", 4);
				OutLevel_(level_);
				Out__Int_(ofs_, 2);
			}
			else {
				if (level_ == 0) {
					if (acc_ == 1) {
						if (op_ == 77) {
							op_ = 108;
							Out__String_(" LDGW1 ", 8);
						}
						else if (op_ == 78) {
							op_ = 110;
							Out__String_(" LDGB1 ", 8);
						}
					}
					else {
						if (op_ == 77) {
							op_ = 109;
							Out__String_(" LDGW2 ", 8);
						}
						else if (op_ == 78) {
							op_ = 111;
							Out__String_(" LDGB2 ", 8);
						}
					}
				}
				else {
					if (acc_ == 1) {
						if (op_ == 77) {
							op_ = 112;
							Out__String_(" LDLW1 ", 8);
						}
						else if (op_ == 78) {
							op_ = 114;
							Out__String_(" LDLB1 ", 8);
						}
					}
					else {
						if (op_ == 77) {
							op_ = 113;
							Out__String_(" LDLW2 ", 8);
						}
						else if (op_ == 78) {
							op_ = 115;
							Out__String_(" LDLB2 ", 8);
						}
					}
				}
				Out__String_("   [", 5);
				OutLevel_(level_);
				Out__Int_(ofs_, 2);
				Out__String_("]", 2);
			}
			OBNC_INC_N(ORG__pcbytes_, 2);
			Out__Ln_();
			code_[OBNC_IT(ORG__pc_, 8000, 688)].op_ = (unsigned char) op_;
			code_[OBNC_IT(ORG__pc_, 8000, 689)].a_ = ofs_;
			OBNC_INC(ORG__pc_);
		}
	}
}


static void PUTInc_(OBNC_INTEGER op_, OBNC_INTEGER a_, OBNC_INTEGER mem_)
{

	if (a_ != 0) {
		if ((mem_ == 1) && (op_ == 1)) {
			if (a_ == 1) {
				PUT0_(18);
			}
			else if (a_ == 2) {
				PUT0_(19);
			}
			else if (a_ == 4) {
				PUT0_(20);
			}
		}
		else if ((mem_ == 1) && (op_ == 2)) {
			if (a_ == 1) {
				PUT0_(24);
			}
			else if (a_ == 2) {
				PUT0_(25);
			}
			else if (a_ == 4) {
				PUT0_(26);
			}
		}
		else if ((mem_ == 0) && (op_ == 1)) {
			if (a_ == 1) {
				PUT0_(15);
			}
			else if (a_ == 2) {
				PUT0_(16);
			}
			else if (a_ == 4) {
				PUT0_(17);
			}
		}
		else if ((mem_ == 0) && (op_ == 2)) {
			if (a_ == 1) {
				PUT0_(21);
			}
			else if (a_ == 2) {
				PUT0_(22);
			}
			else if (a_ == 4) {
				PUT0_(23);
			}
		}
	}
}


static void PUTRel_(OBNC_INTEGER op_, OBNC_INTEGER a_, OBNC_INTEGER cst_)
{

	if (cst_ == 11) {
		if (op_ == 9) {
			PUT0_(78);
		}
		else if (op_ == 10) {
			PUT0_(79);
		}
		else if (op_ == 11) {
			PUT0_(81);
		}
		else if (op_ == 12) {
			PUT0_(80);
		}
	}
	else if (OBNC_IN(cst_, 0xDEu)) {
		if (a_ == 0) {
			if (op_ == 9) {
				PUT0_(60);
			}
			else if (op_ == 10) {
				PUT0_(61);
			}
			else if (op_ == 11) {
				PUT0_(65);
			}
			else if (op_ == 12) {
				PUT0_(64);
			}
			else if (op_ == 13) {
				PUT0_(63);
			}
			else if (op_ == 14) {
				PUT0_(62);
			}
		}
		else {
			if (op_ == 9) {
				PUT0_(54);
			}
			else if (op_ == 10) {
				PUT0_(55);
			}
			else if (op_ == 11) {
				PUT0_(57);
			}
			else if (op_ == 12) {
				PUT0_(59);
			}
			else if (op_ == 13) {
				PUT0_(56);
			}
			else if (op_ == 14) {
				PUT0_(58);
			}
		}
	}
	else if (cst_ == 5) {
		if (a_ == 0) {
			if (op_ == 9) {
				PUT0_(72);
			}
			else if (op_ == 10) {
				PUT0_(73);
			}
			else if (op_ == 11) {
				PUT0_(77);
			}
			else if (op_ == 12) {
				PUT0_(76);
			}
			else if (op_ == 13) {
				PUT0_(75);
			}
			else if (op_ == 14) {
				PUT0_(74);
			}
		}
		else {
			if (op_ == 9) {
				PUT0_(66);
			}
			else if (op_ == 10) {
				PUT0_(67);
			}
			else if (op_ == 11) {
				PUT0_(69);
			}
			else if (op_ == 12) {
				PUT0_(71);
			}
			else if (op_ == 13) {
				PUT0_(68);
			}
			else if (op_ == 14) {
				PUT0_(70);
			}
		}
	}
}


static void loadStringAdr_(ORG__Item_ *x_, const OBNC_Td *x_td, OBNC_INTEGER acc_)
{

	PUTLoad_(81, (*x_).r_, (*x_).a_, acc_);
	(*x_).acc_ = acc_;
}


void ORG__loadAdr_(ORG__Item_ *x_, const OBNC_Td *x_td, OBNC_INTEGER acc_)
{

	if ((*x_).mode_ == 2) {
		if ((*x_).acc_ == 0) {
			if (OBNC_IN(acc_, 0x6u)) {
				PUTLoad_(81, (*x_).r_, (*x_).a_, acc_);
			}
			else if (acc_ == 3) {
				ORG__loadAdr_(&(*x_), x_td, 1);
				PUT0_(41);
			}
		}
		else if ((*x_).acc_ == 1) {
			if (acc_ == 2) {
				PUT0_(45);
			}
			else if (acc_ == 3) {
				PUT0_(41);
			}
		}
		else if ((*x_).acc_ == 2) {
			if (acc_ == 1) {
				PUT0_(46);
			}
			else if (acc_ == 3) {
				PUT0_(46);
				PUT0_(41);
			}
		}
		else if ((*x_).acc_ == 3) {
			if (acc_ == 1) {
				PUT0_(42);
			}
			else if (acc_ == 2) {
				PUT0_(43);
			}
		}
	}
	else if ((*x_).mode_ == 3) {
		if ((*x_).acc_ == 0) {
			if (OBNC_IN(acc_, 0x6u)) {
				PUTLoad_(77, (*x_).r_, (*x_).a_, acc_);
			}
			else if (acc_ == 3) {
				ORG__loadAdr_(&(*x_), x_td, 1);
				PUT0_(41);
			}
		}
		else if ((*x_).acc_ == 1) {
			if (acc_ == 2) {
				PUT0_(45);
			}
			else if (acc_ == 3) {
				PUT0_(41);
			}
		}
		else if ((*x_).acc_ == 2) {
			if (acc_ == 1) {
				PUT0_(46);
			}
			else if (acc_ == 2) {
				PUT0_(48);
			}
			else if (acc_ == 3) {
				PUT0_(46);
				PUT0_(41);
			}
		}
		else if ((*x_).acc_ == 3) {
			if (acc_ == 1) {
				PUT0_(42);
			}
			else if (acc_ == 2) {
				PUT0_(43);
			}
		}
	}
	(*x_).acc_ = acc_;
}


void ORG__loadacc_(ORG__Item_ *x_, const OBNC_Td *x_td, OBNC_INTEGER acc_)
{
	OBNC_INTEGER op_;

	if ((*OBNC_PT((*x_).type_, 820)).size_ == 1) {
		op_ = 78;
	}
	else {
		op_ = 77;
	}
	if (((*x_).type_ == ORB__strType_) || ((*OBNC_PT((*x_).type_, 821)).form_ == 12)) {
		ORG__loadAdr_(&(*x_), x_td, acc_);
	}
	else {
		if ((*x_).mode_ == 1) {
			if ((*x_).acc_ == -1) {
				if (acc_ == 1) {
					if ((*OBNC_PT((*x_).type_, 826)).form_ == 11) {
						if ((*x_).b_ == 2) {
							PUT1_(88, OBNC_ORD((unsigned char) (str_[OBNC_IT((*x_).a_ - ORG__varsize_, 2400, 827)])));
						}
						else {
							loadStringAdr_(&(*x_), x_td, 1);
						}
					}
					else {
						PUT1_(88, (*x_).a_);
					}
				}
				else if (acc_ == 2) {
					if ((*OBNC_PT((*x_).type_, 833)).form_ == 11) {
						if ((*x_).b_ == 2) {
							PUT1_(89, OBNC_ORD((unsigned char) (str_[OBNC_IT((*x_).a_ - ORG__varsize_, 2400, 834)])));
						}
						else {
							loadStringAdr_(&(*x_), x_td, 2);
						}
					}
					else {
						PUT1_(89, (*x_).a_);
					}
				}
				else if (acc_ == 3) {
					if (((*OBNC_PT((*x_).type_, 840)).form_ == 11) && ((*x_).b_ == 2)) {
						PUT1_(87, OBNC_ORD((unsigned char) (str_[OBNC_IT((*x_).a_ - ORG__varsize_, 2400, 840)])));
					}
					else if ((*OBNC_PT((*x_).type_, 841)).form_ == 11) {
						if ((*x_).r_ > 0) {
							PUT1_(92, (*x_).a_);
						}
						else if ((*x_).r_ == 0) {
							PUT1_(93, (*x_).a_);
						}
					}
					else {
						PUT1_(87, (*x_).a_);
					}
				}
			}
			else if ((*x_).acc_ == 0) {
				PUTLoad_(81, (*x_).r_, (*x_).a_, 1);
				if (acc_ == 3) {
					PUT0_(41);
				}
			}
			else if ((*x_).acc_ == 1) {
				if (acc_ == 2) {
					PUT0_(45);
				}
				else if (acc_ == 3) {
					PUT0_(41);
				}
			}
			else if ((*x_).acc_ == 2) {
				if (acc_ == 1) {
					PUT0_(46);
				}
				else if (acc_ == 3) {
					PUT0_(46);
					PUT0_(41);
				}
			}
			else if ((*x_).acc_ == 3) {
				if (acc_ == 1) {
					PUT0_(42);
				}
				else if (acc_ == 2) {
					PUT0_(43);
				}
			}
		}
		else if ((*x_).mode_ == 2) {
			if ((*x_).acc_ == 0) {
				if (OBNC_IN(acc_, 0x6u)) {
					PUTLoad_(op_, (*x_).r_, (*x_).a_, acc_);
				}
				else if (acc_ == 3) {
					ORG__loadacc_(&(*x_), x_td, 1);
					PUT0_(41);
				}
			}
			else if ((*x_).acc_ == 1) {
				if (acc_ == 2) {
					PUT0_(45);
				}
				else if (acc_ == 3) {
					PUT0_(41);
				}
			}
			else if ((*x_).acc_ == 2) {
				if (acc_ == 1) {
					PUT0_(46);
				}
				else if (acc_ == 3) {
					PUT0_(46);
					PUT0_(41);
				}
			}
			else if ((*x_).acc_ == 3) {
				if (acc_ == 1) {
					PUT0_(42);
				}
				else if (acc_ == 2) {
					PUT0_(43);
				}
			}
		}
		else if ((*x_).mode_ == 3) {
			if ((*x_).acc_ == 0) {
				if (OBNC_IN(acc_, 0x6u)) {
					PUTLoad_(op_, (*x_).r_, (*x_).a_, acc_);
					if (acc_ == 1) {
						PUT0_(47);
					}
					else if (acc_ == 2) {
						PUT0_(48);
					}
				}
				else if (acc_ == 3) {
					ORG__loadacc_(&(*x_), x_td, 1);
					PUT0_(41);
				}
			}
			else if ((*x_).acc_ == 1) {
				if (acc_ == 1) {
					PUT0_(47);
				}
				else if (acc_ == 2) {
					PUT0_(45);
					PUT0_(48);
				}
				else if (acc_ == 3) {
					PUT0_(47);
					PUT0_(41);
				}
			}
			else if ((*x_).acc_ == 2) {
				if (acc_ == 1) {
					PUT0_(46);
					PUT0_(47);
				}
				else if (acc_ == 2) {
					PUT0_(48);
				}
				else if (acc_ == 3) {
					PUT0_(46);
					PUT0_(41);
				}
			}
			else if ((*x_).acc_ == 3) {
				if (acc_ == 1) {
					PUT0_(42);
				}
				else if (acc_ == 2) {
					PUT0_(43);
				}
			}
		}
		(*x_).acc_ = acc_;
	}
}


void ORG__SysCall_(OBNC_INTEGER sys_)
{

	PUT1_(88, sys_);
	PUT0_(0);
}


void ORG__FixAt_(OBNC_INTEGER L0_, OBNC_INTEGER new_)
{

	Out__String_("; fix instruction at pc=", 25);
	Out__Int_(L0_, 2);
	Out__String_(" with value ", 13);
	Out__Int_(new_, 2);
	Out__String_(" or more precisely: ", 21);
	Out__Int_((new_ - L0_), 3);
	Out__Ln_();
	code_[OBNC_IT(L0_, 8000, 924)].a_ = new_ - L0_;
}


void ORG__FixOr_(OBNC_INTEGER L0_)
{

	PUT1_(98, (L0_ + 1));
}


void ORG__FixIf_(OBNC_INTEGER *L0_)
{

	PUT1_(97, ((*L0_) + 1));
	OBNC_INC((*L0_));
}


void ORG__FixList_(ORG__Ptr_ p_)
{

	while (p_ != 0) {
		if ((*OBNC_PT(p_, 941)).label_ != 0) {
			ORG__FixAt_((*OBNC_PT(p_, 941)).label_, ORG__pc_);
		}
		else if (code_[OBNC_IT((*OBNC_PT(p_, 942)).label_, 8000, 942)].op_ == 32) {
			ORG__FixAt_(((*OBNC_PT(p_, 942)).label_ + 1), ORG__pc_);
		}
		p_ = (*OBNC_PT(p_, 944)).next_;
	}
}


void ORG__FixNot_(OBNC_INTEGER L_)
{

	Out__String_("; fix instruction at pc=", 25);
	Out__Int_(L_, 2);
	Out__String_(" with inverse intruction: ", 27);
	if (code_[OBNC_IT(L_, 8000, 950)].op_ == 54) {
		Out__String_("EQ  => NE  ", 12);
		code_[OBNC_IT(L_, 8000, 950)].op_ = (unsigned char) 55;
	}
	else if (code_[OBNC_IT(L_, 8000, 951)].op_ == 55) {
		Out__String_("NE  => EQ  ", 12);
		code_[OBNC_IT(L_, 8000, 951)].op_ = (unsigned char) 54;
	}
	else if (code_[OBNC_IT(L_, 8000, 952)].op_ == 57) {
		Out__String_("LT  => GE  ", 12);
		code_[OBNC_IT(L_, 8000, 952)].op_ = (unsigned char) 58;
	}
	else if (code_[OBNC_IT(L_, 8000, 953)].op_ == 58) {
		Out__String_("GE  => LT  ", 12);
		code_[OBNC_IT(L_, 8000, 953)].op_ = (unsigned char) 57;
	}
	else if (code_[OBNC_IT(L_, 8000, 954)].op_ == 59) {
		Out__String_("LE  => GT  ", 12);
		code_[OBNC_IT(L_, 8000, 954)].op_ = (unsigned char) 56;
	}
	else if (code_[OBNC_IT(L_, 8000, 955)].op_ == 56) {
		Out__String_("GT  => LE  ", 12);
		code_[OBNC_IT(L_, 8000, 955)].op_ = (unsigned char) 59;
	}
	else if (code_[OBNC_IT(L_, 8000, 956)].op_ == 60) {
		Out__String_("EQ0 => NE0 ", 12);
		code_[OBNC_IT(L_, 8000, 956)].op_ = (unsigned char) 61;
	}
	else if (code_[OBNC_IT(L_, 8000, 957)].op_ == 61) {
		Out__String_("NE0 => EQ0 ", 12);
		code_[OBNC_IT(L_, 8000, 957)].op_ = (unsigned char) 60;
	}
	else if (code_[OBNC_IT(L_, 8000, 958)].op_ == 62) {
		Out__String_("GE0 => LT0 ", 12);
		code_[OBNC_IT(L_, 8000, 958)].op_ = (unsigned char) 65;
	}
	else if (code_[OBNC_IT(L_, 8000, 959)].op_ == 63) {
		Out__String_("GT0 => LE0 ", 12);
		code_[OBNC_IT(L_, 8000, 959)].op_ = (unsigned char) 64;
	}
	else if (code_[OBNC_IT(L_, 8000, 960)].op_ == 64) {
		Out__String_("LE0 => GT0 ", 12);
		code_[OBNC_IT(L_, 8000, 960)].op_ = (unsigned char) 63;
	}
	else if (code_[OBNC_IT(L_, 8000, 961)].op_ == 65) {
		Out__String_("LT0 => GE0 ", 12);
		code_[OBNC_IT(L_, 8000, 961)].op_ = (unsigned char) 62;
	}
	else if (code_[OBNC_IT(L_, 8000, 962)].op_ == 78) {
		Out__String_("SEQ => SNE ", 12);
		code_[OBNC_IT(L_, 8000, 962)].op_ = (unsigned char) 79;
	}
	else if (code_[OBNC_IT(L_, 8000, 963)].op_ == 79) {
		Out__String_("SNE => SEQ ", 12);
		code_[OBNC_IT(L_, 8000, 963)].op_ = (unsigned char) 78;
	}
	else {
		Out__Ln_();
		Out__String_("Finaly nevermind, just add a 'NOT' instruction here", 52);
		PUT0_(32);
	}
	Out__Ln_();
}


OBNC_INTEGER ORG__Here_(void)
{
	return ORG__pc_;
}


void ORG__JumpExit_(void)
{

	PUT1_(96, ORG__pc_);
}


void ORG__JumpWhile_(OBNC_INTEGER L_)
{

	ORG__JumpExit_();
	ORG__FixAt_((ORG__pc_ - 1), L_);
}


void ORG__JumpRepeat_(ORG__Ptr_ p_, OBNC_INTEGER L_)
{

	while (p_ != 0) {
		if ((*OBNC_PT(p_, 987)).label_ != 0) {
			ORG__FixAt_((*OBNC_PT(p_, 987)).label_, L_);
		}
		p_ = (*OBNC_PT(p_, 989)).next_;
	}
}


static void NilCheck_(void)
{

	PUTTrap_(4, 0);
}


static void LoadAdrxy_(ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{

	if (((*x_).acc_ == -1) || ((*x_).acc_ == 0)) {
		if ((*y_).acc_ == 0) {
			ORG__loadAdr_(&(*x_), x_td, 1);
			ORG__loadAdr_(&(*y_), y_td, 2);
		}
		else if ((*y_).acc_ == 1) {
			PUT0_(45);
			ORG__loadAdr_(&(*x_), x_td, 1);
		}
		else if ((*y_).acc_ == 2) {
			ORG__loadAdr_(&(*x_), x_td, 1);
		}
	}
	else if ((*x_).acc_ == 1) {
		if ((*y_).acc_ == 0) {
			ORG__loadAdr_(&(*y_), y_td, 2);
		}
		else if ((*y_).acc_ == 1) {
			(*x_).acc_ = 0;
			(*y_).acc_ = 0;
			ORG__loadAdr_(&(*x_), x_td, 1);
			ORG__loadAdr_(&(*y_), y_td, 2);
		}
	}
	else {
		if ((*y_).acc_ == 0) {
			ORG__loadAdr_(&(*x_), x_td, 1);
			ORG__loadAdr_(&(*y_), y_td, 2);
		}
		else if ((*y_).acc_ == 1) {
			(*x_).acc_ = 0;
			(*y_).acc_ = 0;
			ORG__loadAdr_(&(*x_), x_td, 1);
			ORG__loadAdr_(&(*y_), y_td, 2);
		}
	}
}


static void loadTypTagAdr_(ORB__Type_ T_, OBNC_INTEGER acc_)
{
	ORG__Item_ x_ = {0};

	x_.mode_ = 2;
	x_.a_ = (*OBNC_PT(T_, 1016)).len_;
	x_.r_ = -(*OBNC_PT(T_, 1016)).mno_;
	ORG__loadAdr_(&x_, &ORG__Item_td, acc_);
	x_.acc_ = acc_;
}


void ORG__MakeConstItem_(ORG__Item_ *x_, const OBNC_Td *x_td, ORB__Type_ typ_, OBNC_INTEGER val_)
{

	(*x_).mode_ = 1;
	(*x_).type_ = typ_;
	(*x_).a_ = val_;
	(*x_).acc_ = -1;
	(*x_).Lseq_ = 0;
	(*x_).Lexit_ = 0;
	(*x_).Lnext_ = 0;
}


void ORG__MakeRealItem_(ORG__Item_ *x_, const OBNC_Td *x_td, OBNC_REAL val_)
{

	(*x_).mode_ = 1;
	(*x_).type_ = ORB__realType_;
	(*x_).a_ = OBNC_VAL(OBNC_INTEGER, val_);
	(*x_).acc_ = -1;
	(*x_).Lseq_ = 0;
	(*x_).Lexit_ = 0;
	(*x_).Lnext_ = 0;
}


void ORG__MakeStringItem_(ORG__Item_ *x_, const OBNC_Td *x_td, OBNC_INTEGER len_)
{
	OBNC_INTEGER i_;

	(*x_).mode_ = 1;
	(*x_).type_ = ORB__strType_;
	(*x_).a_ = strx_ + ORG__varsize_;
	(*x_).b_ = len_;
	i_ = 0;
	if (((strx_ + len_) + 4) < 2400) {
		while (len_ > 0) {
			str_[OBNC_IT(strx_, 2400, 1037)] = ORS__str_[OBNC_IT(i_, 256, 1037)];
			OBNC_INC(strx_);
			OBNC_INC(i_);
			OBNC_DEC(len_);
		}
		while ((OBNC_MOD(strx_, 4)) != 0) {
			str_[OBNC_IT(strx_, 2400, 1038)] = '\x00';
			OBNC_INC(strx_);
		}
	}
	else {
		ORS__Mark_("too many strings", 17);
	}
	(*x_).acc_ = -1;
	(*x_).Lseq_ = 0;
	(*x_).Lexit_ = 0;
	(*x_).Lnext_ = 0;
}


void ORG__MakeItem_(ORG__Item_ *x_, const OBNC_Td *x_td, ORB__Object_ y_, OBNC_INTEGER curlev_)
{

	(*x_).mode_ = (*OBNC_PT(y_, 1046)).class_;
	(*x_).type_ = (*OBNC_PT(y_, 1046)).type_;
	(*x_).a_ = (*OBNC_PT(y_, 1046)).val_;
	(*x_).rdo_ = (*OBNC_PT(y_, 1046)).rdo_;
	if ((*OBNC_PT(y_, 1047)).class_ == 3) {
		(*x_).b_ = 0;
		(*x_).r_ = 1;
	}
	else if (((*OBNC_PT(y_, 1048)).class_ == 1) && ((*OBNC_PT((*OBNC_PT(y_, 1048)).type_, 1048)).form_ == 11)) {
		(*x_).b_ = (*OBNC_PT(y_, 1048)).lev_;
	}
	else {
		(*x_).r_ = (*OBNC_PT(y_, 1050)).lev_;
	}
	if ((((*OBNC_PT(y_, 1051)).lev_ > 0) && ((*OBNC_PT(y_, 1051)).lev_ != curlev_)) && ((*OBNC_PT(y_, 1051)).class_ != 1)) {
		ORS__Mark_("not accessible ", 16);
	}
	(*x_).acc_ = 0;
	OBNC_COPY_ARRAY((*OBNC_PT(y_, 1052)).name_, (*x_).name_, 32);
	(*x_).Lseq_ = 0;
	(*x_).Lexit_ = 0;
	(*x_).Lnext_ = 0;
}


void ORG__Field_(ORG__Item_ *x_, const OBNC_Td *x_td, ORB__Object_ y_)
{

	if ((*x_).mode_ == 2) {
		if (((*x_).r_ >= 0) && ((*x_).acc_ != 1)) {
			(*x_).a_ = (*x_).a_ + (*OBNC_PT(y_, 1062)).val_;
		}
		else {
			ORG__loadAdr_(&(*x_), x_td, 1);
			if (OBNC_IN((*OBNC_PT(y_, 1063)).val_, 0x17u)) {
				PUTInc_(1, (*OBNC_PT(y_, 1063)).val_, 0);
			}
			else {
				PUT1_(89, (*OBNC_PT(y_, 1063)).val_);
				PUT0_(1);
			}
			(*x_).mode_ = 3;
		}
	}
	else if ((*x_).mode_ == 3) {
		ORG__loadAdr_(&(*x_), x_td, 1);
		if (OBNC_IN((*OBNC_PT(y_, 1066)).val_, 0x17u)) {
			PUTInc_(1, (*OBNC_PT(y_, 1066)).val_, 0);
		}
		else {
			PUT1_(89, (*OBNC_PT(y_, 1066)).val_);
			PUT0_(1);
		}
		(*x_).mode_ = 3;
	}
}


void ORG__Index_(ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{
	OBNC_INTEGER s_, lim_;

	s_ = (*OBNC_PT((*OBNC_PT((*x_).type_, 1072)).base_, 1072)).size_;
	lim_ = (*OBNC_PT((*x_).type_, 1072)).len_;
	if (((*y_).mode_ == 1) && (lim_ >= 0)) {
		if (((*y_).a_ < 0) || ((*y_).a_ >= lim_)) {
			ORS__Mark_("bad index", 10);
		}
		if (! (((*y_).acc_ == -1) && ((*y_).a_ == 0))) {
			if ((*x_).mode_ == 2) {
				if (((*x_).r_ >= 0) && ((*x_).acc_ != 1)) {
					(*x_).a_ = ((*y_).a_ * s_) + (*x_).a_;
				}
				else {
					(*x_).a_ = (*y_).a_ * s_;
					if (OBNC_IN((*x_).a_, 0x17u)) {
						PUTInc_(1, (*x_).a_, 1);
					}
					else {
						PUT1_(89, (*x_).a_);
						PUT0_(27);
					}
					(*x_).a_ = 0;
				}
			}
			else if ((*x_).mode_ == 3) {
				(*x_).b_ = ((*y_).a_ * s_) + (*x_).b_;
			}
		}
	}
	else {
		if (! ((((*OBNC_PT((*y_).type_, 1087)).form_ == 4) && ((*y_).acc_ == -1)) && ((*y_).a_ == 0))) {
			if ((*x_).acc_ == 1) {
				(*x_).acc_ = 3;
				PUT0_(41);
			}
			ORG__loadacc_(&(*y_), y_td, 1);
			if (lim_ < 0) {
				if (OBNC_IN((*x_).mode_, 0xCu)) {
					PUTLoad_(77, 1, ((*x_).a_ + 4), 2);
					lim_ = -1;
				}
				else {
					ORS__Mark_("error in Index", 15);
				}
			}
			PUTTrap_(1, lim_);
			if (s_ == 4) {
				PUT1_(89, 2);
				PUT0_(33);
			}
			else if (s_ > 1) {
				PUT1_(89, s_);
				PUT0_(3);
			}
			PUT0_(45);
			if ((*x_).acc_ == 3) {
				PUT0_(42);
				(*x_).acc_ = 1;
			}
			else {
				ORG__loadAdr_(&(*x_), x_td, 1);
			}
			PUT0_(1);
		}
		(*x_).mode_ = 3;
	}
}


void ORG__DeRef_(ORG__Item_ *x_, const OBNC_Td *x_td)
{

	ORG__loadAdr_(&(*x_), x_td, 1);
	PUT0_(47);
	NilCheck_();
}


static void Q_(ORB__Type_ T_, OBNC_INTEGER *dcw_)
{

	if ((*OBNC_PT(T_, 1116)).base_ != 0) {
		Q_((*OBNC_PT(T_, 1117)).base_, &(*dcw_));
		data_[OBNC_IT((*dcw_), 160, 1117)] = (((((*OBNC_PT(T_, 1117)).mno_ * 4096) + (*OBNC_PT(T_, 1117)).len_) * 4096) + (*dcw_)) - fixorgT_;
		fixorgT_ = (*dcw_);
		OBNC_INC((*dcw_));
	}
}


static void FindPtrFlds_(ORB__Type_ typ_, OBNC_INTEGER off_, OBNC_INTEGER *dcw_)
{
	ORB__Object_ fld_ = 0;
	OBNC_INTEGER i_, s_;

	if (((*OBNC_PT(typ_, 1125)).form_ == 7) || ((*OBNC_PT(typ_, 1125)).form_ == 8)) {
		data_[OBNC_IT((*dcw_), 160, 1125)] = off_;
		OBNC_INC((*dcw_));
	}
	else if ((*OBNC_PT(typ_, 1126)).form_ == 13) {
		fld_ = (*OBNC_PT(typ_, 1127)).dsc_;
		while (fld_ != 0) {
			FindPtrFlds_((*OBNC_PT(fld_, 1128)).type_, ((*OBNC_PT(fld_, 1128)).val_ + off_), &(*dcw_));
			fld_ = (*OBNC_PT(fld_, 1128)).next_;
		}
	}
	else if ((*OBNC_PT(typ_, 1129)).form_ == 12) {
		s_ = (*OBNC_PT((*OBNC_PT(typ_, 1130)).base_, 1130)).size_;
		for (i_ = 0; i_ <= (*OBNC_PT(typ_, 1131)).len_ - 1; i_ += 1) {
			FindPtrFlds_((*OBNC_PT(typ_, 1131)).base_, ((i_ * s_) + off_), &(*dcw_));
		}
	}
}


void ORG__BuildTD_(ORB__Type_ T_, OBNC_INTEGER *dc_)
{
	OBNC_INTEGER dcw_, k_, s_;

	dcw_ = OBNC_DIV((*dc_), 4);
	s_ = (*OBNC_PT(T_, 1137)).size_;
	if (s_ <= 24) {
		s_ = 32;
	}
	else if (s_ <= 56) {
		s_ = 64;
	}
	else if (s_ <= 120) {
		s_ = 128;
	}
	else {
		s_ = (OBNC_DIV(s_ + 263, 256)) * 256;
	}
	(*OBNC_PT(T_, 1141)).len_ = (*dc_);
	data_[OBNC_IT(dcw_, 160, 1141)] = s_;
	OBNC_INC(dcw_);
	k_ = (*OBNC_PT(T_, 1142)).nofpar_;
	if (k_ > 3) {
		ORS__Mark_("ext level too large", 20);
	}
	else {
		Q_(T_, &dcw_);
		while (k_ < 3) {
			data_[OBNC_IT(dcw_, 160, 1145)] = -1;
			OBNC_INC(dcw_);
			OBNC_INC(k_);
		}
	}
	FindPtrFlds_(T_, 0, &dcw_);
	data_[OBNC_IT(dcw_, 160, 1147)] = -1;
	OBNC_INC(dcw_);
	tdx_ = dcw_;
	(*dc_) = dcw_ * 4;
	if (tdx_ >= 160) {
		ORS__Mark_("too many record types", 22);
		tdx_ = 0;
	}
}


void ORG__TypeTest_(ORG__Item_ *x_, const OBNC_Td *x_td, ORB__Type_ T_, int varpar_, int isguard_)
{
	OBNC_INTEGER tmp_;

	if (T_ != 0) {
		if (varpar_) {
			PUTLoad_(77, (*x_).r_, ((*x_).a_ + 4), 1);
			PUT0_(47);
			tmp_ = (*OBNC_PT(T_, 1157)).nofpar_ * 4;
			if (OBNC_IN(tmp_, 0x17u)) {
				PUTInc_(1, tmp_, 1);
			}
			else {
				PUT1_(89, tmp_);
				PUT0_(27);
			}
		}
		else {
			ORG__loadAdr_(&(*x_), x_td, 1);
			PUT1_(89, 8);
			PUT0_(28);
			PUT0_(47);
			tmp_ = (*OBNC_PT(T_, 1161)).nofpar_ * 4;
			if (OBNC_IN(tmp_, 0x17u)) {
				PUTInc_(1, tmp_, 1);
			}
			else {
				PUT1_(89, tmp_);
				PUT0_(27);
			}
			(*x_).acc_ = 0;
			(*x_).a_ = (*x_).a_ + 8;
		}
		loadTypTagAdr_(T_, 2);
		PUT0_(82);
		if (isguard_) {
			PUTTrap_(2, 0);
		}
	}
	else {
		PUT1_(88, 1);
	}
}


void ORG__CopyPtrs_(ORG__Ptr_ *x_, ORG__Ptr_ *y_)
{
	ORG__Ptr_ Lx_ = 0, Ly_ = 0;
	OBNC_INTEGER tmp_;

	Lx_ = (*x_);
	Ly_ = (*y_);
	if ((*y_) != 0) {
		if ((*x_) == 0) {
			while (Ly_ != 0) {
				if (Lx_ == 0) {
					OBNC_NEW(Lx_, &ORG__Exit_td, struct ORG__Exit_Heap, OBNC_REGULAR_ALLOC);
					(*x_) = Lx_;
				}
				else {
					OBNC_NEW((*OBNC_PT(Lx_, 1183)).next_, &ORG__Exit_td, struct ORG__Exit_Heap, OBNC_REGULAR_ALLOC);
					Lx_ = (*OBNC_PT(Lx_, 1183)).next_;
				}
				(*OBNC_PT(Lx_, 1184)).label_ = (*OBNC_PT(Ly_, 1184)).label_;
				Ly_ = (*OBNC_PT(Ly_, 1184)).next_;
			}
		}
		else {
			while (Ly_ != 0) {
				tmp_ = 0;
				Lx_ = (*x_);
				while ((*OBNC_PT(Lx_, 1189)).next_ != 0) {
					if ((*OBNC_PT(Lx_, 1189)).label_ == (*OBNC_PT(Ly_, 1189)).label_) {
						tmp_ = 1;
					}
					Lx_ = (*OBNC_PT(Lx_, 1189)).next_;
				}
				if ((tmp_ == 0) && ((*OBNC_PT(Lx_, 1190)).label_ != (*OBNC_PT(Ly_, 1190)).label_)) {
					OBNC_NEW((*OBNC_PT(Lx_, 1191)).next_, &ORG__Exit_td, struct ORG__Exit_Heap, OBNC_REGULAR_ALLOC);
					Lx_ = (*OBNC_PT(Lx_, 1191)).next_;
					(*OBNC_PT(Lx_, 1192)).label_ = (*OBNC_PT(Ly_, 1193)).label_;
				}
				Ly_ = (*OBNC_PT(Ly_, 1194)).next_;
			}
		}
	}
}


void ORG__AddPtr_(ORG__Ptr_ *x_, OBNC_INTEGER L0_)
{
	ORG__Ptr_ Lx_ = 0;
	OBNC_INTEGER tmp_;

	if ((*x_) == 0) {
		OBNC_NEW((*x_), &ORG__Exit_td, struct ORG__Exit_Heap, OBNC_REGULAR_ALLOC);
		(*OBNC_PT((*x_), 1204)).label_ = L0_;
	}
	else {
		Lx_ = (*x_);
		tmp_ = 0;
		while ((*OBNC_PT(Lx_, 1206)).next_ != 0) {
			if ((*OBNC_PT(Lx_, 1206)).label_ == L0_) {
				tmp_ = 1;
			}
			Lx_ = (*OBNC_PT(Lx_, 1206)).next_;
		}
		if ((tmp_ == 0) && ((*OBNC_PT(Lx_, 1207)).label_ != L0_)) {
			OBNC_NEW((*OBNC_PT(Lx_, 1208)).next_, &ORG__Exit_td, struct ORG__Exit_Heap, OBNC_REGULAR_ALLOC);
			Lx_ = (*OBNC_PT(Lx_, 1208)).next_;
			(*OBNC_PT(Lx_, 1209)).label_ = L0_;
		}
	}
}


static void displaylist_(const struct ORG__Item_ *x_)
{
	ORG__Ptr_ Lcur_ = 0;

	Out__String_("LSEQ: ", 7);
	Lcur_ = (*x_).Lseq_;
	while (Lcur_ != 0) {
		Out__Int_((*OBNC_PT(Lcur_, 1217)).label_, 4);
		Lcur_ = (*OBNC_PT(Lcur_, 1217)).next_;
	}
	Out__Ln_();
	Out__String_("LNEXT: ", 8);
	Lcur_ = (*x_).Lnext_;
	while (Lcur_ != 0) {
		Out__Int_((*OBNC_PT(Lcur_, 1218)).label_, 4);
		Lcur_ = (*OBNC_PT(Lcur_, 1218)).next_;
	}
	Out__Ln_();
	Out__String_("LEXIT: ", 8);
	Lcur_ = (*x_).Lexit_;
	while (Lcur_ != 0) {
		Out__Int_((*OBNC_PT(Lcur_, 1219)).label_, 4);
		Lcur_ = (*OBNC_PT(Lcur_, 1219)).next_;
	}
	Out__Ln_();
}


void ORG__Not_(ORG__Item_ *x_, const OBNC_Td *x_td)
{
	ORG__Ptr_ Lcur_ = 0;

	if (1) {
		Out__String_("Not DEB", 8);
		Out__Ln_();
	}
	if ((((*x_).Lseq_ == 0) && ((*x_).Lnext_ == 0)) && ((*x_).Lexit_ == 0)) {
		ORG__FixNot_((ORG__pc_ - 1));
	}
	else {
		if (1) {
			displaylist_(&(*x_));
		}
		ORG__FixList_((*x_).Lseq_);
		ORG__FixList_((*x_).Lexit_);
		(*x_).Lseq_ = 0;
		(*x_).Lexit_ = 0;
		ORG__AddPtr_(&(*x_).Lseq_, ORG__pc_);
		PUT0_(32);
		if (1) {
			WSTR_("After exchange:", 16);
			displaylist_(&(*x_));
		}
	}
	if (1) {
		Out__String_("Not FIN", 8);
		Out__Ln_();
	}
}


void ORG__SubPtr_(ORG__Ptr_ *x_, OBNC_INTEGER L0_)
{
	ORG__Ptr_ Lx1_ = 0, Lx2_ = 0;

	if ((*x_) != 0) {
		if (((*OBNC_PT((*x_), 1253)).next_ == 0) && ((*OBNC_PT((*x_), 1253)).label_ == L0_)) {
			(*x_) = 0;
		}
		else if (((*OBNC_PT((*x_), 1254)).next_ != 0) && ((*OBNC_PT((*x_), 1254)).label_ == L0_)) {
			(*x_) = (*OBNC_PT((*x_), 1255)).next_;
		}
		else if ((*OBNC_PT((*x_), 1255)).next_ != 0) {
			Lx1_ = (*x_);
			Lx2_ = (*OBNC_PT((*x_), 1255)).next_;
			while ((Lx2_ != 0) && ((*OBNC_PT(Lx2_, 1256)).label_ != L0_)) {
				Lx1_ = (*OBNC_PT(Lx1_, 1256)).next_;
				Lx2_ = (*OBNC_PT(Lx2_, 1256)).next_;
			}
			if (Lx2_ != 0) {
				(*OBNC_PT(Lx1_, 1257)).next_ = (*OBNC_PT(Lx2_, 1257)).next_;
			}
		}
	}
}


void ORG__And1_(ORG__Item_ *x_, const OBNC_Td *x_td)
{
	OBNC_INTEGER tmp_;
	ORG__Ptr_ Lcur_ = 0;

	if (1) {
		Out__String_("And1 DEB", 9);
		Out__Ln_();
	}
	tmp_ = ORG__pc_ - 1;
	ORG__FixIf_(&tmp_);
	if (tmp_ != (ORG__pc_ - 1)) {
		ORG__FixList_((*x_).Lexit_);
	}
	ORG__AddPtr_(&(*x_).Lexit_, (ORG__pc_ - 1));
	ORG__SubPtr_(&(*x_).Lseq_, (ORG__pc_ - 1));
	if (1) {
		Out__String_("LSEQ: ", 7);
		Lcur_ = (*x_).Lseq_;
		while (Lcur_ != 0) {
			Out__Int_((*OBNC_PT(Lcur_, 1275)).label_, 4);
			Lcur_ = (*OBNC_PT(Lcur_, 1275)).next_;
		}
		Out__Ln_();
		Out__String_("LNEXT: ", 8);
		Lcur_ = (*x_).Lnext_;
		while (Lcur_ != 0) {
			Out__Int_((*OBNC_PT(Lcur_, 1276)).label_, 4);
			Lcur_ = (*OBNC_PT(Lcur_, 1276)).next_;
		}
		Out__Ln_();
		Out__String_("LEXIT: ", 8);
		Lcur_ = (*x_).Lexit_;
		while (Lcur_ != 0) {
			Out__Int_((*OBNC_PT(Lcur_, 1277)).label_, 4);
			Lcur_ = (*OBNC_PT(Lcur_, 1277)).next_;
		}
		Out__Ln_();
		Out__String_("And1 FIN", 9);
		Out__Ln_();
	}
}


void ORG__And2_(ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{
	ORG__Ptr_ Lcur_ = 0;
	OBNC_INTEGER tmp_;

	tmp_ = 0;
	if (1) {
		Out__String_("And2 DEB", 9);
		Out__Ln_();
	}
	ORG__CopyPtrs_(&(*x_).Lseq_, &(*y_).Lseq_);
	ORG__CopyPtrs_(&(*x_).Lnext_, &(*y_).Lnext_);
	ORG__CopyPtrs_(&(*x_).Lexit_, &(*y_).Lexit_);
	if (1) {
		Out__String_("LSEQ: ", 7);
		Lcur_ = (*x_).Lseq_;
		while (Lcur_ != 0) {
			Out__Int_((*OBNC_PT(Lcur_, 1300)).label_, 4);
			Lcur_ = (*OBNC_PT(Lcur_, 1300)).next_;
		}
		Out__Ln_();
		Out__String_("LNEXT: ", 8);
		Lcur_ = (*x_).Lnext_;
		while (Lcur_ != 0) {
			Out__Int_((*OBNC_PT(Lcur_, 1301)).label_, 4);
			Lcur_ = (*OBNC_PT(Lcur_, 1301)).next_;
		}
		Out__Ln_();
		Out__String_("LEXIT: ", 8);
		Lcur_ = (*x_).Lexit_;
		while (Lcur_ != 0) {
			Out__Int_((*OBNC_PT(Lcur_, 1302)).label_, 4);
			Lcur_ = (*OBNC_PT(Lcur_, 1302)).next_;
		}
		Out__Ln_();
		Out__String_("And2 FIN", 9);
		Out__Ln_();
	}
}


void ORG__Or1_(ORG__Item_ *x_, const OBNC_Td *x_td)
{
	OBNC_INTEGER tmp_;
	ORG__Ptr_ Lcur_ = 0;

	if (1) {
		Out__String_("Or1 DEB", 8);
		Out__Ln_();
	}
	tmp_ = ORG__pc_;
	ORG__FixOr_((ORG__pc_ - 1));
	if (tmp_ != ORG__pc_) {
		ORG__FixList_((*x_).Lexit_);
	}
	ORG__AddPtr_(&(*x_).Lseq_, (ORG__pc_ - 1));
	ORG__SubPtr_(&(*x_).Lexit_, (ORG__pc_ - 1));
	ORG__CopyPtrs_(&(*x_).Lnext_, &(*x_).Lexit_);
	(*x_).Lexit_ = 0;
	if (1) {
		Out__String_("LSEQ: ", 7);
		Lcur_ = (*x_).Lseq_;
		while (Lcur_ != 0) {
			Out__Int_((*OBNC_PT(Lcur_, 1324)).label_, 4);
			Lcur_ = (*OBNC_PT(Lcur_, 1324)).next_;
		}
		Out__Ln_();
		Out__String_("LNEXT: ", 8);
		Lcur_ = (*x_).Lnext_;
		while (Lcur_ != 0) {
			Out__Int_((*OBNC_PT(Lcur_, 1325)).label_, 4);
			Lcur_ = (*OBNC_PT(Lcur_, 1325)).next_;
		}
		Out__Ln_();
		Out__String_("LEXIT: ", 8);
		Lcur_ = (*x_).Lexit_;
		while (Lcur_ != 0) {
			Out__Int_((*OBNC_PT(Lcur_, 1326)).label_, 4);
			Lcur_ = (*OBNC_PT(Lcur_, 1326)).next_;
		}
		Out__Ln_();
		Out__String_("Or1 FIN", 8);
		Out__Ln_();
	}
}


void ORG__Or2_(ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{
	ORG__Ptr_ Lcur_ = 0;
	OBNC_INTEGER tmp_;

	tmp_ = 0;
	if (1) {
		Out__String_("Or2 DEB", 8);
		Out__Ln_();
	}
	ORG__CopyPtrs_(&(*x_).Lseq_, &(*y_).Lseq_);
	ORG__CopyPtrs_(&(*x_).Lnext_, &(*y_).Lnext_);
	ORG__CopyPtrs_(&(*x_).Lexit_, &(*y_).Lexit_);
	if (1) {
		Out__String_("LSEQ: ", 7);
		Lcur_ = (*x_).Lseq_;
		while (Lcur_ != 0) {
			Out__Int_((*OBNC_PT(Lcur_, 1345)).label_, 4);
			Lcur_ = (*OBNC_PT(Lcur_, 1345)).next_;
		}
		Out__Ln_();
		Out__String_("LNEXT: ", 8);
		Lcur_ = (*x_).Lnext_;
		while (Lcur_ != 0) {
			Out__Int_((*OBNC_PT(Lcur_, 1346)).label_, 4);
			Lcur_ = (*OBNC_PT(Lcur_, 1346)).next_;
		}
		Out__Ln_();
		Out__String_("LEXIT: ", 8);
		Lcur_ = (*x_).Lexit_;
		while (Lcur_ != 0) {
			Out__Int_((*OBNC_PT(Lcur_, 1347)).label_, 4);
			Lcur_ = (*OBNC_PT(Lcur_, 1347)).next_;
		}
		Out__Ln_();
		Out__String_("Or2 FIN", 8);
		Out__Ln_();
	}
}


void ORG__Neg_(ORG__Item_ *x_, const OBNC_Td *x_td)
{

	if ((*OBNC_PT((*x_).type_, 1358)).form_ == 4) {
		if ((*x_).mode_ == 1) {
			(*x_).a_ = -(*x_).a_;
		}
		else {
			ORG__loadacc_(&(*x_), x_td, 1);
			PUT0_(6);
		}
	}
	else if ((*OBNC_PT((*x_).type_, 1362)).form_ == 5) {
		if ((*x_).mode_ == 1) {
			(*x_).a_ = ((*x_).a_ + 2147483647) + 1;
		}
		else {
			ORG__loadacc_(&(*x_), x_td, 1);
			PUT0_(12);
		}
	}
	else {
		if ((*x_).mode_ == 1) {
			(*x_).a_ = (-(*x_).a_) - 1;
		}
		else {
			ORG__loadacc_(&(*x_), x_td, 1);
			PUT1_(89, -1);
			PUT0_(40);
		}
	}
}


void ORG__AddOp_(OBNC_INTEGER op_, ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{

	if (((*x_).mode_ == 1) && ((*y_).mode_ == 1)) {
		if (op_ == 6) {
			(*x_).a_ = (*x_).a_ + (*y_).a_;
		}
		else if (op_ == 7) {
			(*x_).a_ = (*x_).a_ - (*y_).a_;
		}
	}
	else {
		if (op_ == 6) {
			op_ = 1;
		}
		else {
			op_ = 2;
		}
		if (((*y_).mode_ == 1) && ((*x_).mode_ != 1)) {
			ORG__loadacc_(&(*x_), x_td, 1);
			if (OBNC_IN((*y_).a_, 0x17u)) {
				PUTInc_(op_, (*y_).a_, 0);
			}
			else {
				ORG__loadacc_(&(*y_), y_td, 2);
				PUT0_(op_);
			}
		}
		else if ((*x_).mode_ == 1) {
			ORG__loadacc_(&(*y_), y_td, 1);
			if (OBNC_IN((*x_).a_, 0x17u)) {
				PUTInc_(op_, (*x_).a_, 0);
			}
			else {
				ORG__loadacc_(&(*x_), x_td, 2);
				PUT0_(op_);
			}
			if (op_ == 2) {
				PUT0_(6);
			}
			(*x_).acc_ = 1;
			(*y_).acc_ = 2;
			(*x_).mode_ = (*y_).mode_;
		}
		else {
			if ((*y_).acc_ == 1) {
				PUT0_(45);
				(*y_).acc_ = 2;
			}
			else if ((*x_).acc_ == 2) {
				PUT0_(46);
				(*x_).acc_ = 1;
			}
			ORG__loadacc_(&(*x_), x_td, 1);
			ORG__loadacc_(&(*y_), y_td, 2);
			PUT0_(op_);
		}
	}
	if ((*x_).mode_ == 3) {
		(*x_).mode_ = 2;
	}
	if ((*y_).mode_ == 3) {
		(*y_).mode_ = 2;
	}
}


static OBNC_INTEGER log2_(OBNC_INTEGER m_, OBNC_INTEGER *e_)
{

	(*e_) = 0;
	while (! OBNC_ODD(m_)) {
		m_ = OBNC_DIV(m_, 2);
		OBNC_INC((*e_));
	}
	return m_;
}


void ORG__MulOp_(ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{
	OBNC_INTEGER e_;

	if (((*x_).mode_ == 1) && ((*y_).mode_ == 1)) {
		(*x_).a_ = (*x_).a_ * (*y_).a_;
	}
	else {
		if ((*y_).mode_ == 1) {
			if (((*y_).a_ >= 2) && (log2_((*y_).a_, &e_) == 1)) {
				ORG__loadacc_(&(*x_), x_td, 1);
				PUT1_(89, e_);
				PUT0_(33);
			}
			else if ((*y_).a_ == 1) {
				ORG__loadacc_(&(*x_), x_td, 1);
			}
			else if ((*y_).a_ == 0) {
				PUT1_(88, 0);
			}
			else {
				ORG__loadacc_(&(*x_), x_td, 1);
				PUT1_(89, (*y_).a_);
				PUT0_(3);
			}
		}
		else if ((*x_).mode_ == 1) {
			if (((*x_).a_ >= 2) && (log2_((*x_).a_, &e_) == 1)) {
				ORG__loadacc_(&(*y_), y_td, 1);
				PUT1_(89, e_);
				PUT0_(33);
			}
			else if ((*x_).a_ == 1) {
				ORG__loadacc_(&(*y_), y_td, 1);
			}
			else if ((*x_).a_ == 0) {
				PUT1_(88, 0);
			}
			else {
				ORG__loadacc_(&(*y_), y_td, 1);
				PUT1_(89, (*x_).a_);
				PUT0_(3);
			}
			(*x_).acc_ = 1;
			(*y_).acc_ = 2;
			(*x_).mode_ = (*y_).mode_;
		}
		else {
			if ((*y_).acc_ == 1) {
				PUT0_(45);
				(*y_).acc_ = 2;
			}
			else if ((*x_).acc_ == 2) {
				PUT0_(46);
				(*x_).acc_ = 1;
			}
			ORG__loadacc_(&(*x_), x_td, 1);
			ORG__loadacc_(&(*y_), y_td, 2);
			PUT0_(3);
		}
	}
	if ((*x_).mode_ == 3) {
		(*x_).mode_ = 2;
	}
	if ((*y_).mode_ == 3) {
		(*y_).mode_ = 2;
	}
}


void ORG__DivOp_(OBNC_INTEGER op_, ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{
	OBNC_INTEGER e_;

	if (op_ == 3) {
		if (((*x_).mode_ == 1) && ((*y_).mode_ == 1)) {
			if ((*y_).a_ > 0) {
				(*x_).a_ = OBNC_DIV((*x_).a_, (*y_).a_);
			}
			else {
				ORS__Mark_("bad divisor", 12);
			}
		}
		else if ((*y_).mode_ == 1) {
			if (((*y_).a_ >= 2) && (log2_((*y_).a_, &e_) == 1)) {
				ORG__loadacc_(&(*x_), x_td, 1);
				PUT1_(89, e_);
				PUT0_(34);
			}
			else if ((*y_).a_ == 0) {
				ORS__Mark_("division by 0", 14);
			}
			else if ((*y_).a_ == 1) {
				ORG__loadacc_(&(*x_), x_td, 1);
			}
			else {
				ORG__loadacc_(&(*x_), x_td, 1);
				PUT1_(89, (*y_).a_);
				PUT0_(4);
			}
		}
		else if ((*x_).mode_ == 1) {
			if ((*x_).a_ == 0) {
				PUT1_(88, 0);
			}
			else {
				ORG__loadacc_(&(*x_), x_td, 1);
				PUTTrap_(6, 0);
				ORG__loadacc_(&(*y_), y_td, 2);
				PUT0_(4);
			}
			(*x_).acc_ = 1;
			(*y_).acc_ = 2;
			(*x_).mode_ = (*y_).mode_;
		}
		else {
			if ((*y_).acc_ == 1) {
				PUT0_(45);
				(*y_).acc_ = 2;
			}
			else if ((*x_).acc_ == 2) {
				PUT0_(46);
				(*x_).acc_ = 1;
			}
			ORG__loadacc_(&(*x_), x_td, 1);
			PUTTrap_(6, 0);
			ORG__loadacc_(&(*y_), y_td, 2);
			PUT0_(4);
		}
	}
	else {
		if (((*x_).mode_ == 1) && ((*y_).mode_ == 1)) {
			if ((*y_).a_ > 0) {
				(*x_).a_ = OBNC_DIV((*x_).a_, (*y_).a_);
			}
			else {
				ORS__Mark_("bad modulus", 12);
			}
		}
		else if ((*y_).mode_ == 1) {
			if ((*y_).a_ == 0) {
				ORS__Mark_("division by 0", 14);
			}
			else if ((*y_).a_ == 1) {
				ORG__loadacc_(&(*x_), x_td, 1);
			}
			else {
				ORG__loadacc_(&(*x_), x_td, 1);
				PUT1_(89, (*y_).a_);
				PUT0_(13);
			}
		}
		else if ((*x_).mode_ == 1) {
			if ((*x_).a_ == 0) {
				PUT1_(88, 0);
			}
			else {
				ORG__loadacc_(&(*x_), x_td, 1);
				PUTTrap_(6, 0);
				ORG__loadacc_(&(*y_), y_td, 2);
				PUT0_(13);
			}
			(*x_).acc_ = 1;
			(*y_).acc_ = 2;
			(*x_).mode_ = (*y_).mode_;
		}
		else {
			if ((*y_).acc_ == 1) {
				PUT0_(45);
				(*y_).acc_ = 2;
			}
			else if ((*x_).acc_ == 2) {
				PUT0_(46);
				(*x_).acc_ = 1;
			}
			ORG__loadacc_(&(*x_), x_td, 1);
			PUTTrap_(6, 0);
			ORG__loadacc_(&(*y_), y_td, 2);
			PUT0_(13);
		}
	}
	if ((*x_).mode_ == 3) {
		(*x_).mode_ = 2;
	}
	if ((*y_).mode_ == 3) {
		(*y_).mode_ = 2;
	}
}


void ORG__RealOp_(OBNC_INTEGER op_, ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{

	if ((*y_).acc_ == 1) {
		PUT0_(45);
		(*y_).acc_ = 2;
	}
	else if ((*x_).acc_ == 2) {
		PUT0_(46);
		(*x_).acc_ = 1;
	}
	ORG__loadacc_(&(*x_), x_td, 1);
	ORG__loadacc_(&(*y_), y_td, 2);
	if (op_ == 6) {
		PUT0_(7);
	}
	else if (op_ == 7) {
		PUT0_(8);
	}
	else if (op_ == 1) {
		PUT0_(9);
	}
	else if (op_ == 2) {
		PUT0_(10);
	}
	if ((*x_).mode_ == 3) {
		(*x_).mode_ = 2;
	}
	if ((*y_).mode_ == 3) {
		(*y_).mode_ = 2;
	}
}


void ORG__Singleton_(ORG__Item_ *x_, const OBNC_Td *x_td)
{

	if ((*x_).mode_ == 1) {
		(*x_).a_ = OBNC_LSL(1, (*x_).a_);
	}
	else {
		PUT1_(88, 1);
		ORG__loadacc_(&(*x_), x_td, 2);
		PUT0_(33);
		(*x_).acc_ = 1;
	}
}


void ORG__Set_(ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{
	OBNC_INTEGER L0_, L1_;

	if (((*x_).mode_ == 1) && ((*y_).mode_ == 1)) {
		if ((*x_).a_ <= (*y_).a_) {
			(*x_).a_ = OBNC_LSL(2, (*y_).a_) - OBNC_LSL(1, (*x_).a_);
		}
		else {
			(*x_).a_ = 0;
		}
	}
	else {
		ORG__loadacc_(&(*x_), x_td, 1);
		ORG__loadacc_(&(*y_), y_td, 2);
		PUT1_(99, ORG__pc_);
		L0_ = ORG__pc_;
		(*x_).acc_ = 0;
		(*y_).acc_ = 0;
		if (((*x_).mode_ == 1) && ((*y_).mode_ != 1)) {
			PUT1_(88, -2);
			ORG__loadacc_(&(*y_), y_td, 2);
			PUT0_(33);
			PUT1_(89, OBNC_LSL(-1, (*x_).a_));
		}
		else if (((*x_).mode_ != 1) && ((*y_).mode_ == 1)) {
			PUT1_(88, -1);
			ORG__loadacc_(&(*x_), x_td, 2);
			PUT0_(33);
			PUT1_(89, OBNC_LSL(-2, (*y_).a_));
		}
		else {
			PUT1_(88, -2);
			ORG__loadacc_(&(*y_), y_td, 2);
			PUT0_(33);
			PUT0_(41);
			PUT1_(88, -1);
			ORG__loadacc_(&(*x_), x_td, 2);
			PUT0_(33);
			PUT0_(43);
		}
		PUT0_(40);
		(*x_).acc_ = 1;
		(*y_).acc_ = 2;
		ORG__JumpExit_();
		L1_ = ORG__pc_;
		ORG__FixAt_((L0_ - 1), L1_);
		PUT1_(88, 0);
		(*x_).mode_ = 1;
		(*x_).acc_ = -1;
		(*x_).a_ = 0;
		ORG__FixAt_((L1_ - 1), ORG__pc_);
	}
}


void ORG__In_(ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{

	ORG__loadacc_(&(*x_), x_td, 2);
	ORG__loadacc_(&(*y_), y_td, 1);
	PUT0_(31);
	(*x_).acc_ = 1;
	(*x_).mode_ = (*y_).mode_;
}


void ORG__SetOp_(OBNC_INTEGER op_, ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{
	unsigned OBNC_INTEGER xset_, yset_;

	if (((*x_).mode_ == 1) && ((*y_).mode_ == 1)) {
		xset_ = OBNC_VAL(unsigned OBNC_INTEGER, (*x_).a_);
		yset_ = OBNC_VAL(unsigned OBNC_INTEGER, (*y_).a_);
		if (op_ == 6) {
			xset_ = xset_ | yset_;
		}
		else if (op_ == 7) {
			xset_ = xset_ & ~ yset_;
		}
		else if (op_ == 1) {
			xset_ = xset_ & yset_;
		}
		else if (op_ == 2) {
			xset_ = xset_ ^ yset_;
		}
		(*x_).a_ = OBNC_VAL(OBNC_INTEGER, xset_);
	}
	else {
		if ((*y_).acc_ == 1) {
			PUT0_(45);
			(*y_).acc_ = 2;
		}
		else if ((*x_).acc_ == 2) {
			PUT0_(46);
			(*x_).acc_ = 1;
		}
		ORG__loadacc_(&(*x_), x_td, 1);
		ORG__loadacc_(&(*y_), y_td, 2);
		if (op_ == 6) {
			PUT0_(39);
		}
		else if (op_ == 7) {
			PUT0_(38);
		}
		else if (op_ == 1) {
			PUT0_(37);
		}
		else if (op_ == 2) {
			PUT0_(40);
		}
	}
}


static void Loadxy_(ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{

	if (((*x_).acc_ == -1) || ((*x_).acc_ == 0)) {
		if ((*y_).acc_ <= 0) {
			ORG__loadacc_(&(*x_), x_td, 1);
			ORG__loadacc_(&(*y_), y_td, 2);
		}
		else if ((*y_).acc_ == 1) {
			PUT0_(45);
			ORG__loadacc_(&(*x_), x_td, 1);
		}
		else if ((*y_).acc_ == 2) {
			ORG__loadacc_(&(*x_), x_td, 1);
		}
	}
	else if ((*x_).acc_ == 1) {
		if ((*y_).acc_ <= 0) {
			ORG__loadacc_(&(*x_), x_td, 1);
			ORG__loadacc_(&(*y_), y_td, 2);
		}
		else if ((*y_).acc_ == 1) {
			ORG__loadacc_(&(*y_), y_td, 2);
			ORG__loadacc_(&(*x_), x_td, 1);
		}
	}
	else {
		if ((*y_).acc_ == 0) {
			ORG__loadacc_(&(*x_), x_td, 1);
			ORG__loadacc_(&(*y_), y_td, 2);
		}
		else if ((*y_).acc_ == 1) {
			(*x_).acc_ = 0;
			(*y_).acc_ = 0;
			ORG__loadacc_(&(*x_), x_td, 1);
			ORG__loadacc_(&(*y_), y_td, 2);
		}
	}
}


void ORG__IntRealRelation_(OBNC_INTEGER op_, ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{

	if ((((*x_).mode_ == 1) && ((*y_).mode_ == 1)) && ((*OBNC_PT((*x_).type_, 1595)).form_ != 11)) {
		if (((*x_).acc_ == -1) && ((*y_).acc_ == -1)) {
			switch (op_) {
				case 9:
					if ((*x_).a_ == (*y_).a_) {
						PUT1_(88, 1);
					}
					else {
						PUT1_(88, 0);
					}
					break;
				case 10:
					if ((*x_).a_ != (*y_).a_) {
						PUT1_(88, 1);
					}
					else {
						PUT1_(88, 0);
					}
					break;
				case 11:
					if ((*x_).a_ < (*y_).a_) {
						PUT1_(88, 1);
					}
					else {
						PUT1_(88, 0);
					}
					break;
				case 12:
					if ((*x_).a_ <= (*y_).a_) {
						PUT1_(88, 1);
					}
					else {
						PUT1_(88, 0);
					}
					break;
				case 13:
					if ((*x_).a_ > (*y_).a_) {
						PUT1_(88, 1);
					}
					else {
						PUT1_(88, 0);
					}
					break;
				case 14:
					if ((*x_).a_ >= (*y_).a_) {
						PUT1_(88, 1);
					}
					else {
						PUT1_(88, 0);
					}
					break;
				default:
					OBNC_CT(1597);
			}
		}
		else if (((*x_).acc_ != -1) && ((*y_).acc_ == -1)) {
			ORG__loadacc_(&(*x_), x_td, 1);
			if ((*y_).a_ != 0) {
				PUT1_(89, (*y_).a_);
			}
			PUTRel_(op_, (*y_).a_, (*OBNC_PT((*x_).type_, 1608)).form_);
		}
		else if (((*x_).acc_ == -1) && ((*y_).acc_ != -1)) {
			if (op_ == 11) {
				op_ = 13;
			}
			else if (op_ == 12) {
				op_ = 14;
			}
			else if (op_ == 13) {
				op_ = 11;
			}
			else if (op_ == 14) {
				op_ = 12;
			}
			ORG__loadacc_(&(*y_), y_td, 1);
			if ((*x_).a_ != 0) {
				PUT1_(89, (*x_).a_);
			}
			PUTRel_(op_, (*x_).a_, (*OBNC_PT((*x_).type_, 1617)).form_);
		}
		else {
			Loadxy_(&(*x_), x_td, &(*y_), y_td);
			PUTRel_(op_, 1, (*OBNC_PT((*x_).type_, 1620)).form_);
		}
	}
	else {
		if (((*x_).mode_ == 1) && ((*y_).mode_ != 1)) {
			if (op_ == 11) {
				op_ = 13;
			}
			else if (op_ == 12) {
				op_ = 14;
			}
			else if (op_ == 13) {
				op_ = 11;
			}
			else if (op_ == 14) {
				op_ = 12;
			}
			if ((*x_).acc_ == -1) {
				if ((*OBNC_PT((*x_).type_, 1631)).form_ == 11) {
					Loadxy_(&(*y_), y_td, &(*x_), x_td);
				}
				else if ((*x_).a_ != 0) {
					Loadxy_(&(*y_), y_td, &(*x_), x_td);
				}
				else {
					ORG__loadacc_(&(*y_), y_td, 1);
				}
				PUTRel_(op_, (*x_).a_, (*OBNC_PT((*x_).type_, 1638)).form_);
			}
			else {
				Loadxy_(&(*x_), x_td, &(*y_), y_td);
				PUTRel_(op_, 1, (*OBNC_PT((*x_).type_, 1641)).form_);
			}
			(*x_).mode_ = (*y_).mode_;
			(*x_).acc_ = 1;
		}
		else if (((*x_).mode_ != 1) && ((*y_).mode_ == 1)) {
			if ((*y_).acc_ == -1) {
				if ((*OBNC_PT((*y_).type_, 1646)).form_ == 11) {
					Loadxy_(&(*x_), x_td, &(*y_), y_td);
				}
				else if ((*y_).a_ != 0) {
					Loadxy_(&(*x_), x_td, &(*y_), y_td);
				}
				else {
					ORG__loadacc_(&(*x_), x_td, 1);
				}
				PUTRel_(op_, (*y_).a_, (*OBNC_PT((*x_).type_, 1653)).form_);
			}
			else {
				Loadxy_(&(*x_), x_td, &(*y_), y_td);
				PUTRel_(op_, 1, (*OBNC_PT((*x_).type_, 1656)).form_);
			}
		}
		else {
			Loadxy_(&(*x_), x_td, &(*y_), y_td);
			PUTRel_(op_, 1, (*OBNC_PT((*x_).type_, 1660)).form_);
		}
	}
}


void ORG__StringRelation_(OBNC_INTEGER op_, ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{

	if ((op_ == 14) || (op_ == 13)) {
		if ((*OBNC_PT((*y_).type_, 1669)).form_ == 11) {
			loadStringAdr_(&(*y_), y_td, 1);
		}
		else {
			ORG__loadAdr_(&(*y_), y_td, 1);
		}
		if ((*OBNC_PT((*x_).type_, 1670)).form_ == 11) {
			loadStringAdr_(&(*x_), x_td, 2);
		}
		else {
			ORG__loadAdr_(&(*x_), x_td, 2);
		}
		if (op_ == 14) {
			op_ = 12;
		}
		else {
			op_ = 11;
		}
		(*x_).mode_ = (*y_).mode_;
		(*x_).acc_ = 1;
		(*y_).acc_ = 2;
	}
	else {
		if ((*OBNC_PT((*x_).type_, 1674)).form_ == 11) {
			loadStringAdr_(&(*x_), x_td, 1);
		}
		else {
			ORG__loadAdr_(&(*x_), x_td, 1);
		}
		if ((*OBNC_PT((*y_).type_, 1675)).form_ == 11) {
			loadStringAdr_(&(*y_), y_td, 2);
		}
		else {
			ORG__loadAdr_(&(*y_), y_td, 2);
		}
	}
	PUTRel_(op_, 0, 11);
}


void ORG__Push_(ORG__Item_ *x_, const OBNC_Td *x_td)
{

	ORG__loadacc_(&(*x_), x_td, 3);
}


void ORG__Pop_(ORG__Item_ *x_, const OBNC_Td *x_td, OBNC_INTEGER acc_)
{

	if (acc_ == 1) {
		PUT0_(42);
	}
	else if (acc_ == 2) {
		PUT0_(43);
	}
	(*x_).acc_ = acc_;
}


void ORG__PushAdd_(ORG__Item_ *x_, const OBNC_Td *x_td, OBNC_INTEGER L0_)
{
	OBNC_INTEGER tmp_;

	Out__String_("; Add an instruction push between instruction ", 47);
	Out__Int_((L0_ - 1), 2);
	Out__String_(" and instruction ", 18);
	Out__Int_(L0_, 2);
	Out__Ln_();
	(*x_).acc_ = 3;
	tmp_ = ORG__pc_;
	do {
		code_[OBNC_IT(tmp_, 8000, 1702)] = code_[OBNC_IT(tmp_ - 1, 8000, 1702)];
		OBNC_DEC(tmp_);
	} while (! (tmp_ == L0_));
	code_[OBNC_IT(tmp_, 8000, 1703)].op_ = (unsigned char) 41;
	OBNC_INC(ORG__pc_);
	OBNC_INC(ORG__pcbytes_);
}


void ORG__StrToChar_(ORG__Item_ *x_, const OBNC_Td *x_td)
{

	(*x_).type_ = ORB__charType_;
	OBNC_DEC_N(strx_, 4);
	(*x_).a_ = OBNC_ORD((unsigned char) (str_[OBNC_IT((*x_).a_ - ORG__varsize_, 2400, 1709)]));
}


static ORB__Object_ SearchObjByName_(const struct ORG__Item_ *x_)
{
	ORB__Object_ s_ = 0, obj_ = 0;
	OBNC_INTEGER i_;

	s_ = ORB__topScope_;
	if ((*x_).r_ >= 0) {
		do {
			obj_ = (*OBNC_PT(s_, 1718)).next_;
			while ((obj_ != 0) && (OBNC_CMP((*OBNC_PT(obj_, 1719)).name_, 32, (*x_).name_, 32) != 0)) {
				obj_ = (*OBNC_PT(obj_, 1719)).next_;
			}
			s_ = (*OBNC_PT(s_, 1721)).dsc_;
		} while (! ((obj_ != 0) || (s_ == 0)));
	}
	else {
		if (OBNC_IS((*OBNC_PT(s_, 1723)).next_, OBNC_TD((*OBNC_PT(s_, 1723)).next_, struct ORB__ObjDesc_Heap), &ORB__ModDesc_id, 1)) {
			obj_ = (*OBNC_PT(s_, 1723)).next_;
		}
		else {
			obj_ = (*OBNC_PT(s_, 1723)).dsc_;
		}
		i_ = 1;
		while (i_ <= (-(*x_).r_)) {
			obj_ = (*OBNC_PT(obj_, 1726)).next_;
			if ((OBNC_CMP((*OBNC_PT(obj_, 1727)).name_, 32, "SYSTEM", 7) != 0) && (OBNC_CMP((*OBNC_PT(obj_, 1727)).name_, 32, "Out2", 5) != 0)) {
				OBNC_INC(i_);
			}
		}
	}
	if ((*x_).r_ < 0) {
		obj_ = (*OBNC_PT(obj_, 1731)).dsc_;
		while (OBNC_CMP((*x_).name_, 32, (*OBNC_PT(obj_, 1732)).name_, 32) != 0) {
			obj_ = (*OBNC_PT(obj_, 1732)).next_;
		}
	}
	return obj_;
}


static void StoreProc_(ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{
	ORB__Object_ xobj_ = 0, yobj_ = 0;

	yobj_ = SearchObjByName_(&(*y_));
	xobj_ = SearchObjByName_(&(*x_));
	(*OBNC_PT(xobj_, 1742)).lev_ = (*y_).r_;
	(*OBNC_PT(xobj_, 1743)).val_ = (*OBNC_PT(yobj_, 1743)).val_;
}


void ORG__Store_(ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{
	OBNC_INTEGER op_;

	if ((*OBNC_PT((*x_).type_, 1749)).form_ == 10) {
		StoreProc_(&(*x_), x_td, &(*y_), y_td);
	}
	else {
		if ((*OBNC_PT((*x_).type_, 1751)).size_ == 1) {
			op_ = 80;
		}
		else {
			op_ = 79;
		}
		if ((*x_).mode_ == 2) {
			if ((*y_).acc_ == -1) {
				PUTStore_(op_, (*y_).a_, (*x_).r_, (*x_).a_, (*y_).acc_);
			}
			else {
				ORG__loadacc_(&(*y_), y_td, 1);
				PUTStore_(op_, (*y_).a_, (*x_).r_, (*x_).a_, (*y_).acc_);
			}
		}
		else if ((*x_).mode_ == 3) {
			if ((*y_).acc_ == -1) {
				ORG__loadAdr_(&(*x_), x_td, 1);
				PUTStoreM_(op_, (*y_).a_);
			}
			else {
				ORG__loadacc_(&(*y_), y_td, 2);
				ORG__loadAdr_(&(*x_), x_td, 1);
				PUT0_(49);
			}
		}
	}
}


void ORG__StoreStruct_(ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{
	OBNC_INTEGER s_, len_;

	WSTR_("STORESTRUCT", 12);
	if ((*OBNC_PT((*x_).type_, 1777)).form_ == 12) {
		s_ = (*OBNC_PT((*OBNC_PT((*y_).type_, 1778)).base_, 1778)).size_;
		len_ = (*OBNC_PT((*x_).type_, 1779)).len_;
		if (s_ == 1) {
			if (len_ < 0) {
				PUTLoad_(77, (*y_).r_, ((*y_).a_ + 4), 1);
				PUTLoad_(77, (*x_).r_, ((*x_).a_ + 4), 2);
				PUTTrap_(1, -1);
				ORG__loadAdr_(&(*x_), x_td, 1);
				ORG__loadAdr_(&(*y_), y_td, 2);
				PUT0_(52);
			}
			else if ((*OBNC_PT((*y_).type_, 1786)).len_ < 0) {
				PUTLoad_(77, (*y_).r_, ((*y_).a_ + 4), 1);
				PUTTrap_(1, len_);
				ORG__loadAdr_(&(*x_), x_td, 1);
				ORG__loadAdr_(&(*y_), y_td, 2);
				PUT0_(52);
			}
			else {
				PUT1_(88, (*OBNC_PT((*y_).type_, 1792)).len_);
				PUTTrap_(1, len_);
				ORG__loadAdr_(&(*x_), x_td, 1);
				ORG__loadAdr_(&(*y_), y_td, 2);
				PUT0_(52);
			}
		}
		else {
			if (len_ < 0) {
				PUTLoad_(77, (*y_).r_, ((*y_).a_ + 4), 1);
				PUTLoad_(77, (*x_).r_, ((*x_).a_ + 4), 2);
				PUTTrap_(1, -2);
				PUT0_(41);
				ORG__loadAdr_(&(*x_), x_td, 1);
				ORG__loadAdr_(&(*y_), y_td, 2);
				PUT0_(53);
				PUT0_(42);
			}
			else if ((*OBNC_PT((*y_).type_, 1805)).len_ < 0) {
				PUTLoad_(77, (*y_).r_, ((*y_).a_ + 4), 1);
				PUT1_(89, len_);
				PUTTrap_(1, -2);
				PUT0_(41);
				ORG__loadAdr_(&(*x_), x_td, 1);
				ORG__loadAdr_(&(*y_), y_td, 2);
				PUT0_(53);
				PUT0_(42);
			}
			else {
				PUT1_(88, (*OBNC_PT((*y_).type_, 1813)).len_);
				PUT1_(89, len_);
				PUTTrap_(1, -2);
				PUT0_(41);
				ORG__loadAdr_(&(*x_), x_td, 1);
				ORG__loadAdr_(&(*y_), y_td, 2);
				PUT0_(53);
				PUT0_(42);
			}
		}
	}
	else if ((*OBNC_PT((*x_).type_, 1821)).form_ == 13) {
		WINT_((*OBNC_PT((*x_).type_, 1822)).size_);
		PUT1_(87, (*OBNC_PT((*x_).type_, 1823)).size_);
		ORG__loadAdr_(&(*x_), x_td, 1);
		ORG__loadAdr_(&(*y_), y_td, 2);
		PUT0_(53);
		PUT0_(42);
	}
	else {
		ORS__Mark_("inadmissible assignment", 24);
	}
}


void ORG__CopyString_(ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{
	OBNC_INTEGER len_;

	len_ = (*OBNC_PT((*x_).type_, 1835)).len_;
	if (len_ >= 0) {
		if (len_ < (*y_).b_) {
			ORS__Mark_("string too long", 16);
		}
	}
	else {
		PUT1_(88, (*y_).b_);
		PUTLoad_(77, 1, ((*x_).a_ + 4), 2);
		PUTTrap_(1, -1);
	}
	ORG__loadAdr_(&(*x_), x_td, 1);
	loadStringAdr_(&(*y_), y_td, 2);
	PUT0_(52);
}


void ORG__OpenArrayParam_(ORG__Item_ *x_, const OBNC_Td *x_td)
{

	ORG__loadAdr_(&(*x_), x_td, 1);
	PUT0_(41);
	if ((*OBNC_PT((*x_).type_, 1849)).len_ >= 0) {
		PUT1_(87, (*OBNC_PT((*x_).type_, 1849)).len_);
	}
	else {
		PUTLoad_(77, (*x_).r_, ((*x_).a_ + 4), 1);
		PUT0_(41);
	}
}


void ORG__VarParam_(ORG__Item_ *x_, const OBNC_Td *x_td, ORB__Type_ ftype_)
{
	OBNC_INTEGER xmd_;

	xmd_ = (*x_).mode_;
	ORG__loadAdr_(&(*x_), x_td, 1);
	PUT0_(41);
	if (((*OBNC_PT(ftype_, 1856)).form_ == 12) && ((*OBNC_PT(ftype_, 1856)).len_ < 0)) {
		if ((*OBNC_PT((*x_).type_, 1857)).len_ >= 0) {
			PUT1_(87, (*OBNC_PT((*x_).type_, 1857)).len_);
		}
		else {
			PUTLoad_(77, (*x_).r_, ((*x_).a_ + 4), 1);
			PUT0_(41);
		}
	}
	else if ((*OBNC_PT(ftype_, 1859)).form_ == 13) {
		if (xmd_ == 3) {
			PUTLoad_(77, (*x_).r_, ((*x_).a_ + 4), 1);
			PUT0_(41);
		}
		else {
			loadTypTagAdr_((*x_).type_, 3);
		}
	}
}


void ORG__ValueParam_(ORG__Item_ *x_, const OBNC_Td *x_td)
{

	ORG__loadacc_(&(*x_), x_td, 3);
}


void ORG__StringParam_(ORG__Item_ *x_, const OBNC_Td *x_td)
{

	loadStringAdr_(&(*x_), x_td, 1);
	PUT0_(41);
	PUT1_(87, (*x_).b_);
}


void ORG__For0_(ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{

	ORG__Store_(&(*x_), x_td, &(*y_), y_td);
}


void ORG__For1_(ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *z_, const OBNC_Td *z_td)
{

	if ((*x_).acc_ == 1) {
		PUT0_(45);
		(*x_).acc_ = 2;
	}
	else if ((*z_).acc_ == 2) {
		PUT0_(46);
		(*z_).acc_ = 1;
	}
	ORG__loadacc_(&(*z_), z_td, 1);
	ORG__loadacc_(&(*x_), x_td, 2);
	PUT1_(99, ORG__pc_);
	ORG__AddPtr_(&(*x_).Lexit_, (ORG__pc_ - 1));
}


void ORG__For2_(ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *w_, const OBNC_Td *w_td)
{

	(*x_).acc_ = 0;
	ORG__loadAdr_(&(*x_), x_td, 1);
	if ((*w_).mode_ == 1) {
		if (OBNC_IN((*w_).a_, 0x17u)) {
			PUTInc_(1, (*w_).a_, 1);
		}
		else {
			PUT1_(89, (*w_).a_);
			PUT0_(27);
		}
	}
	else {
		ORG__loadacc_(&(*w_), w_td, 2);
		PUT0_(27);
	}
}


void ORG__PrepCall_(ORG__Item_ *x_, const OBNC_Td *x_td, OBNC_INTEGER *r_)
{

	PUT1_(95, ORG__pc_);
	if ((*x_).mode_ > 3) {
		ORG__loadacc_(&(*x_), x_td, 1);
	}
	(*r_) = ORG__pc_;
}


void ORG__Call_(ORG__Item_ *x_, const OBNC_Td *x_td, OBNC_INTEGER r_)
{

	PUTCall_((*x_).r_, (*x_).a_);
	Out__String_("; Replace instruction 'PUSHRET @ret<", 37);
	Out__Int_((r_ - 1), 2);
	Out__String_(">' by instruction 'PUSHRET @ret<+", 34);
	Out__Int_(((ORG__pc_ - r_) + 1), 2);
	Out__String_(">'", 3);
	Out__Ln_();
	code_[OBNC_IT(r_ - 1, 8000, 1921)].a_ = (ORG__pc_ - r_) + 1;
	if ((*OBNC_PT((*OBNC_PT((*x_).type_, 1922)).base_, 1922)).form_ != 9) {
		(*x_).acc_ = 1;
	}
}


void ORG__Enter_(OBNC_INTEGER parblksize_, OBNC_INTEGER locblksize_, OBNC_INTEGER *prevframe_)
{

	(*prevframe_) = frame_;
	frame_ = parblksize_;
	if (locblksize_ != 0) {
		PUT1_(94, locblksize_);
	}
}


void ORG__Return_(OBNC_INTEGER form_, ORG__Item_ *x_, const OBNC_Td *x_td, OBNC_INTEGER size_, OBNC_INTEGER prevframe_)
{

	if (form_ != 9) {
		ORG__loadacc_(&(*x_), x_td, 1);
	}
	PUT0_(44);
	frame_ = prevframe_;
}


void ORG__Increment_(OBNC_INTEGER upordown_, ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{
	OBNC_INTEGER op_, v_;

	if (upordown_ == 0) {
		op_ = 1;
	}
	else {
		op_ = 2;
	}
	if ((*x_).type_ == ORB__byteType_) {
		v_ = 1;
	}
	else {
		v_ = 0;
	}
	if ((*OBNC_PT((*y_).type_, 1946)).form_ == 9) {
		(*y_).mode_ = 1;
		(*y_).a_ = 1;
	}
	if (((*x_).mode_ == 2) && ((*x_).r_ >= 0)) {
		ORG__loadAdr_(&(*x_), x_td, 1);
		if ((((*y_).mode_ == 1) && ((*OBNC_PT((*y_).type_, 1949)).form_ != 10)) && (OBNC_IN((*y_).a_, 0x17u))) {
			PUTInc_(op_, (*y_).a_, 1);
		}
		else {
			ORG__loadacc_(&(*y_), y_td, 2);
			if (op_ == 1) {
				PUT0_(27);
			}
			else {
				PUT0_(28);
			}
		}
	}
	(*x_).acc_ = 1;
}


void ORG__Include_(OBNC_INTEGER inorex_, ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{
	OBNC_INTEGER op_;

	ORG__loadAdr_(&(*x_), x_td, 1);
	if (inorex_ == 0) {
		op_ = 39;
	}
	else {
		op_ = 38;
	}
	ORG__loadacc_(&(*y_), y_td, 2);
	if (op_ == 39) {
		PUT0_(50);
	}
	else {
		PUT0_(51);
	}
}


void ORG__Assert_(ORG__Item_ *x_, const OBNC_Td *x_td)
{

	PUTTrap_(7, 0);
}


void ORG__New_(ORG__Item_ *x_, const OBNC_Td *x_td)
{

	ORG__loadAdr_(&(*x_), x_td, 1);
	loadTypTagAdr_((*OBNC_PT((*x_).type_, 1971)).base_, 1);
	PUTTrap_(0, 0);
}


void ORG__Pack_(ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{
	ORG__Item_ z_ = {0};

	z_ = (*x_);
	ORG__loadacc_(&(*y_), y_td, 1);
	PUT1_(89, 23);
	PUT0_(33);
	PUT0_(45);
	ORG__loadAdr_(&(*x_), x_td, 1);
	PUT0_(27);
}


void ORG__Unpk_(ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{
	ORG__Item_ z_ = {0};

	if ((*y_).mode_ == 1) {
		ORS__Mark_("argument #2 is not const", 25);
	}
	z_ = (*x_);
	ORG__loadacc_(&(*x_), x_td, 1);
	PUT1_(89, 23);
	PUT0_(34);
	PUT1_(89, 127);
	PUT0_(2);
	if ((*y_).r_ >= 0) {
		PUTStore_(79, 0, (*y_).r_, (*y_).a_, 0);
	}
	PUT1_(89, 23);
	PUT0_(33);
	PUT0_(45);
	ORG__loadAdr_(&(*x_), x_td, 1);
	PUT0_(28);
}


void ORG__Get_(ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{

	Loadxy_(&(*x_), x_td, &(*y_), y_td);
	PUT0_(84);
	(*x_).a_ = 0;
	PUTStore_(79, 0, (*y_).r_, (*y_).a_, 1);
}


void ORG__Put_(ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{

	Loadxy_(&(*x_), x_td, &(*y_), y_td);
	PUT0_(83);
	(*x_).type_ = (*y_).type_;
	(*x_).a_ = 0;
}


void ORG__Copy_(void)
{

	PUT0_(53);
	PUT0_(42);
	PUT0_(43);
	PUT0_(42);
}


void ORG__Abs_(ORG__Item_ *x_, const OBNC_Td *x_td)
{

	if ((*x_).mode_ == 1) {
		(*x_).a_ = OBNC_ABS_INT((*x_).a_);
	}
	else {
		ORG__loadacc_(&(*x_), x_td, 1);
		if ((*OBNC_PT((*x_).type_, 2012)).form_ == 5) {
			PUT0_(11);
		}
		else {
			PUT0_(5);
		}
	}
}


void ORG__Odd_(ORG__Item_ *x_, const OBNC_Td *x_td)
{

	ORG__loadacc_(&(*x_), x_td, 1);
	PUT0_(14);
}


void ORG__Floor_(ORG__Item_ *x_, const OBNC_Td *x_td)
{

	ORG__loadacc_(&(*x_), x_td, 1);
	PUT0_(29);
}


void ORG__Float_(ORG__Item_ *x_, const OBNC_Td *x_td)
{

	ORG__loadacc_(&(*x_), x_td, 1);
	PUT0_(30);
}


void ORG__Ord_(ORG__Item_ *x_, const OBNC_Td *x_td)
{

	if (OBNC_IN((*x_).mode_, 0xCu)) {
		ORG__loadacc_(&(*x_), x_td, 1);
	}
}


void ORG__Len_(ORG__Item_ *x_, const OBNC_Td *x_td)
{

	if ((*OBNC_PT((*x_).type_, 2035)).len_ >= 0) {
		(*x_).mode_ = 1;
		(*x_).a_ = (*OBNC_PT((*x_).type_, 2037)).len_;
	}
	else {
		PUTLoad_(77, (*x_).r_, ((*x_).a_ + 4), 1);
		(*x_).acc_ = 1;
	}
}


void ORG__Shift_(OBNC_INTEGER fct_, ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{
	OBNC_INTEGER op_;

	ORG__loadacc_(&(*x_), x_td, 1);
	if (fct_ == 7) {
		op_ = 33;
	}
	else if (fct_ == 8) {
		op_ = 34;
	}
	else if (fct_ == 9) {
		op_ = 36;
	}
	else if (fct_ == 14) {
		op_ = 35;
	}
	ORG__loadacc_(&(*y_), y_td, 2);
	PUT0_(op_);
}


void ORG__ADC_(ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{

	ORG__AddOp_(6, &(*x_), x_td, &(*y_), y_td);
}


void ORG__SBC_(ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{

	ORG__AddOp_(7, &(*x_), x_td, &(*y_), y_td);
}


void ORG__UML_(ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{

	ORG__MulOp_(&(*x_), x_td, &(*y_), y_td);
}


void ORG__Bit_(ORG__Item_ *x_, const OBNC_Td *x_td, ORG__Item_ *y_, const OBNC_Td *y_td)
{

	Loadxy_(&(*x_), x_td, &(*y_), y_td);
	PUT0_(85);
}


void ORG__Adr_(ORG__Item_ *x_, const OBNC_Td *x_td)
{

	if (OBNC_IN((*x_).mode_, 0xCu)) {
		ORG__loadAdr_(&(*x_), x_td, 1);
	}
	else if (((*x_).mode_ == 1) && ((*OBNC_PT((*x_).type_, 2073)).form_ == 10)) {
		ORG__loadacc_(&(*x_), x_td, 1);
	}
	else if (((*x_).mode_ == 1) && ((*OBNC_PT((*x_).type_, 2074)).form_ == 11)) {
		loadStringAdr_(&(*x_), x_td, 1);
	}
	else {
		ORS__Mark_("not addressable", 16);
	}
}


void ORG__Open_(OBNC_INTEGER v_)
{

	ORG__pc_ = 0;
	tdx_ = 0;
	strx_ = 0;
	fixorgP_ = 0;
	fixorgD_ = 0;
	fixorgT_ = 0;
	version_ = v_;
	if (v_ == 0) {
		ORG__pc_ = 1;
		do {
			code_[OBNC_IT(ORG__pc_, 8000, 2082)].op_ = (unsigned char) 0;
			OBNC_INC(ORG__pc_);
		} while (! (ORG__pc_ == 8));
	}
}


void ORG__SetDataSize_(OBNC_INTEGER dc_)
{
	ORB__Object_ obj_ = 0;

	ORG__varsize_ = dc_;
	obj_ = (*OBNC_PT(ORB__topScope_, 2089)).next_;
	while (obj_ != 0) {
		if (((*OBNC_PT(obj_, 2091)).class_ == 1) && ((*OBNC_PT((*OBNC_PT(obj_, 2091)).type_, 2091)).form_ == 11)) {
			(*OBNC_PT(obj_, 2091)).val_ = (*OBNC_PT(obj_, 2091)).val_ + ORG__varsize_;
		}
		obj_ = (*OBNC_PT(obj_, 2093)).next_;
	}
}


void ORG__Header_(void)
{

	entry_ = ORG__pcbytes_;
}


static OBNC_INTEGER NofPtrs_(ORB__Type_ typ_)
{
	ORB__Object_ fld_ = 0;
	OBNC_INTEGER n_;

	if (((*OBNC_PT(typ_, 2103)).form_ == 7) || ((*OBNC_PT(typ_, 2103)).form_ == 8)) {
		n_ = 1;
	}
	else if ((*OBNC_PT(typ_, 2104)).form_ == 13) {
		fld_ = (*OBNC_PT(typ_, 2105)).dsc_;
		n_ = 0;
		while (fld_ != 0) {
			n_ = NofPtrs_((*OBNC_PT(fld_, 2106)).type_) + n_;
			fld_ = (*OBNC_PT(fld_, 2106)).next_;
		}
	}
	else if ((*OBNC_PT(typ_, 2107)).form_ == 12) {
		n_ = NofPtrs_((*OBNC_PT(typ_, 2107)).base_) * (*OBNC_PT(typ_, 2108)).len_;
	}
	else {
		n_ = 0;
	}
	return n_;
}


static void FindPtrs_(Files__Rider_ *R_, const OBNC_Td *R_td, ORB__Type_ typ_, OBNC_INTEGER adr_)
{
	ORB__Object_ fld_ = 0;
	OBNC_INTEGER i_, s_;

	if (((*OBNC_PT(typ_, 2116)).form_ == 7) || ((*OBNC_PT(typ_, 2116)).form_ == 8)) {
		Files__WriteInt_(&(*R_), R_td, adr_);
	}
	else if ((*OBNC_PT(typ_, 2117)).form_ == 13) {
		fld_ = (*OBNC_PT(typ_, 2118)).dsc_;
		while (fld_ != 0) {
			FindPtrs_(&(*R_), R_td, (*OBNC_PT(fld_, 2119)).type_, ((*OBNC_PT(fld_, 2119)).val_ + adr_));
			fld_ = (*OBNC_PT(fld_, 2119)).next_;
		}
	}
	else if ((*OBNC_PT(typ_, 2120)).form_ == 12) {
		s_ = (*OBNC_PT((*OBNC_PT(typ_, 2121)).base_, 2121)).size_;
		for (i_ = 0; i_ <= (*OBNC_PT(typ_, 2122)).len_ - 1; i_ += 1) {
			FindPtrs_(&(*R_), R_td, (*OBNC_PT(typ_, 2122)).base_, ((i_ * s_) + adr_));
		}
	}
}


void ORG__Init_(void)
{

	ORG__pcbytes_ = 0;
}


static OBNC_INTEGER Size_(const ORS__Ident_ name_)
{
	OBNC_INTEGER len_;

	len_ = 0;
	while (name_[OBNC_IT(len_, 32, 2135)] != '\x00') {
		OBNC_INC(len_);
	}
	return len_;
}


void ORG__Close_(ORS__Ident_ modid_, OBNC_INTEGER key_, OBNC_INTEGER nofent_)
{
	ORB__Object_ obj_ = 0;
	OBNC_INTEGER i_, comsize_, nofimps_, nofptrs_, size_, tmp_;
	ORS__Ident_ name_;
	Files__File_ F_ = 0;
	Files__Rider_ R_;
	unsigned char by_;
	int newSF_;

	tmp_ = 0;
	newSF_ = 1;
	obj_ = (*OBNC_PT(ORB__topScope_, 2147)).next_;
	nofimps_ = 0;
	comsize_ = 4;
	nofptrs_ = 0;
	while (obj_ != 0) {
		if ((((*OBNC_PT(obj_, 2149)).class_ == 8) && ((*OBNC_PT(obj_, 2149)).dsc_ != ORB__system_)) && ((*OBNC_PT(obj_, 2149)).dsc_ != ORB__OUT2_)) {
			OBNC_INC(nofimps_);
		}
		else if ((((((*OBNC_PT(obj_, 2150)).exno_ != 0) && ((*OBNC_PT(obj_, 2150)).class_ == 1)) && ((*OBNC_PT((*OBNC_PT(obj_, 2150)).type_, 2150)).form_ == 10)) && ((*OBNC_PT((*OBNC_PT(obj_, 2151)).type_, 2151)).nofpar_ == 0)) && ((*OBNC_PT((*OBNC_PT(obj_, 2151)).type_, 2151)).base_ == ORB__noType_)) {
			i_ = 0;
			while ((*OBNC_PT(obj_, 2152)).name_[OBNC_IT(i_, 32, 2152)] != '\x00') {
				OBNC_INC(i_);
			}
			i_ = (OBNC_DIV(i_ + 4, 4)) * 4;
			OBNC_INC_N(comsize_, i_ + 4);
		}
		else if ((*OBNC_PT(obj_, 2154)).class_ == 2) {
			OBNC_INC_N(nofptrs_, NofPtrs_((*OBNC_PT(obj_, 2154)).type_));
		}
		obj_ = (*OBNC_PT(obj_, 2157)).next_;
	}
	size_ = ((ORG__varsize_ + strx_) + comsize_) + (((((ORG__pc_ + nofimps_) + nofent_) + nofptrs_) + 1) * 4);
	ORB__MakeFileName_(name_, modid_, 32, ".rsc", 5);
	F_ = Files__New_(name_, 32);
	Files__Set_(&R_, &Files__Rider_td, F_, 0);
	Files__WriteString_(&R_, &Files__Rider_td, modid_, 32);
	Files__WriteInt_(&R_, &Files__Rider_td, key_);
	Out__Char_(OBNC_CHR(version_));
	Files__Write_(&R_, &Files__Rider_td, (unsigned char) nofimps_);
	obj_ = (*OBNC_PT(ORB__topScope_, 2163)).next_;
	while ((obj_ != 0) && ((*OBNC_PT(obj_, 2164)).class_ == 8)) {
		if (((*OBNC_PT(obj_, 2165)).dsc_ != ORB__system_) && ((*OBNC_PT(obj_, 2165)).dsc_ != ORB__OUT2_)) {
			Files__WriteString_(&R_, &Files__Rider_td, (*OBNC_PT((*((ORB__Module_*) OBNC_PTT(&(obj_), OBNC_TD(obj_, struct ORB__ModDesc_Heap), &ORB__ModDesc_id, 1, 2165))), 2165)).orgname_, 32);
		}
		obj_ = (*OBNC_PT(obj_, 2167)).next_;
	}
	Out__Char_('\x00');
	Files__WriteInt_(&R_, &Files__Rider_td, (tdx_ * 4));
	i_ = 0;
	while (i_ < tdx_) {
		Files__WriteInt_(&R_, &Files__Rider_td, data_[OBNC_IT(i_, 160, 2171)]);
		OBNC_INC(i_);
	}
	Files__WriteInt_(&R_, &Files__Rider_td, (ORG__varsize_ - (tdx_ * 4)));
	Files__WriteInt_(&R_, &Files__Rider_td, strx_);
	for (i_ = 0; i_ <= strx_ - 1; i_ += 1) {
		Files__Write_(&R_, &Files__Rider_td, (unsigned char) OBNC_ORD((unsigned char) (str_[OBNC_IT(i_, 2400, 2174)])));
		Out__Char_(str_[OBNC_IT(i_, 2400, 2174)]);
	}
	Files__WriteInt_(&R_, &Files__Rider_td, ORG__pcbytes_);
	Files__WriteInt_(&R_, &Files__Rider_td, ORG__pc_);
	for (i_ = 0; i_ <= ORG__pc_ - 1; i_ += 1) {
		Files__Write_(&R_, &Files__Rider_td, code_[OBNC_IT(i_, 8000, 2180)].op_);
		if (code_[OBNC_IT(i_, 8000, 2181)].op_ > 85) {
			if (code_[OBNC_IT(i_, 8000, 2182)].op_ == 86) {
				by_ = (unsigned char) code_[OBNC_IT(i_, 8000, 2182)].a_;
				Files__Write_(&R_, &Files__Rider_td, by_);
				tmp_ = OBNC_ASR(code_[OBNC_IT(i_, 8000, 2182)].a_, 8);
				Files__Write_(&R_, &Files__Rider_td, (unsigned char) tmp_);
				Files__WriteInt_(&R_, &Files__Rider_td, code_[OBNC_IT(i_, 8000, 2182)].b_);
			}
			else if (code_[OBNC_IT(i_, 8000, 2183)].op_ <= 90) {
				Files__WriteInt_(&R_, &Files__Rider_td, code_[OBNC_IT(i_, 8000, 2183)].a_);
			}
			else if (code_[OBNC_IT(i_, 8000, 2184)].op_ <= 116) {
				Files__Write_(&R_, &Files__Rider_td, (unsigned char) code_[OBNC_IT(i_, 8000, 2184)].a_);
			}
			else if (code_[OBNC_IT(i_, 8000, 2185)].op_ <= 121) {
				by_ = (unsigned char) code_[OBNC_IT(i_, 8000, 2185)].a_;
				Files__Write_(&R_, &Files__Rider_td, by_);
				tmp_ = OBNC_ASR(code_[OBNC_IT(i_, 8000, 2185)].a_, 8);
				Files__Write_(&R_, &Files__Rider_td, (unsigned char) tmp_);
			}
			else if (code_[OBNC_IT(i_, 8000, 2186)].op_ <= 123) {
				Files__Write_(&R_, &Files__Rider_td, (unsigned char) code_[OBNC_IT(i_, 8000, 2186)].a_);
				Files__Write_(&R_, &Files__Rider_td, (unsigned char) code_[OBNC_IT(i_, 8000, 2186)].b_);
			}
			else if (code_[OBNC_IT(i_, 8000, 2187)].op_ <= 125) {
				Files__WriteInt_(&R_, &Files__Rider_td, code_[OBNC_IT(i_, 8000, 2187)].a_);
				Files__Write_(&R_, &Files__Rider_td, (unsigned char) code_[OBNC_IT(i_, 8000, 2187)].b_);
			}
			else if (code_[OBNC_IT(i_, 8000, 2188)].op_ <= 150) {
				by_ = (unsigned char) code_[OBNC_IT(i_, 8000, 2188)].a_;
				Files__Write_(&R_, &Files__Rider_td, by_);
				tmp_ = OBNC_ASR(code_[OBNC_IT(i_, 8000, 2188)].a_, 8);
				Files__Write_(&R_, &Files__Rider_td, (unsigned char) tmp_);
			}
			else if (code_[OBNC_IT(i_, 8000, 2189)].op_ <= 155) {
				by_ = (unsigned char) code_[OBNC_IT(i_, 8000, 2189)].a_;
				Files__Write_(&R_, &Files__Rider_td, by_);
				tmp_ = OBNC_ASR(code_[OBNC_IT(i_, 8000, 2189)].a_, 8);
				Files__Write_(&R_, &Files__Rider_td, (unsigned char) tmp_);
				tmp_ = OBNC_ASR(code_[OBNC_IT(i_, 8000, 2189)].a_, 16);
				Files__Write_(&R_, &Files__Rider_td, (unsigned char) tmp_);
			}
			else if (code_[OBNC_IT(i_, 8000, 2190)].op_ <= 157) {
				Files__Write_(&R_, &Files__Rider_td, (unsigned char) code_[OBNC_IT(i_, 8000, 2190)].a_);
				by_ = (unsigned char) code_[OBNC_IT(i_, 8000, 2190)].b_;
				Files__Write_(&R_, &Files__Rider_td, by_);
				tmp_ = OBNC_ASR(code_[OBNC_IT(i_, 8000, 2190)].b_, 8);
				Files__Write_(&R_, &Files__Rider_td, (unsigned char) tmp_);
			}
			else if (code_[OBNC_IT(i_, 8000, 2191)].op_ <= 159) {
				Files__WriteInt_(&R_, &Files__Rider_td, code_[OBNC_IT(i_, 8000, 2191)].a_);
				by_ = (unsigned char) code_[OBNC_IT(i_, 8000, 2191)].b_;
				Files__Write_(&R_, &Files__Rider_td, by_);
				tmp_ = OBNC_ASR(code_[OBNC_IT(i_, 8000, 2191)].b_, 8);
				Files__Write_(&R_, &Files__Rider_td, (unsigned char) tmp_);
			}
		}
	}
	Out__Char_('\x00');
	Files__WriteInt_(&R_, &Files__Rider_td, nofent_);
	obj_ = (*OBNC_PT(ORB__topScope_, 2216)).next_;
	while (obj_ != 0) {
		if ((*OBNC_PT(obj_, 2218)).class_ == 2) {
			FindPtrs_(&R_, &Files__Rider_td, (*OBNC_PT(obj_, 2218)).type_, (*OBNC_PT(obj_, 2218)).val_);
		}
		obj_ = (*OBNC_PT(obj_, 2220)).next_;
	}
	Files__WriteInt_(&R_, &Files__Rider_td, -1);
	Files__WriteInt_(&R_, &Files__Rider_td, entry_);
	Out__Char_('O');
	Files__Register_(F_);
	Files__Close_(F_);
}


void ORG__Init(void)
{
	static int initialized = 0;

	if (! initialized) {
		Out__Init();
		Files__Init();
		ORS__Init();
		ORB__Init();
		initialized = 1;
	}
}
