/*GENERATED BY OBNC 0.16.1*/

#ifndef ORP_h
#define ORP_h

#include <obnc/In.h>
#include <obnc/Out.h>
#include "ORS.h"
#include "ORB.h"
#include "ORG.h"
#include <obnc/OBNC.h>

typedef struct ORP__PtrBaseDesc_ *ORP__PtrBase_;

typedef struct ORP__PtrBaseDesc_ {
	ORS__Ident_ name_;
	ORB__Type_ type_;
	ORP__PtrBase_ next_;
} ORP__PtrBaseDesc_;

struct ORP__PtrBaseDesc_Heap {
	const OBNC_Td *td;
	struct ORP__PtrBaseDesc_ fields;
};

#define ORP__PtrBaseDesc_id compiler__ORP__PtrBaseDesc_id
extern const int ORP__PtrBaseDesc_id;

#define ORP__PtrBaseDesc_ids compiler__ORP__PtrBaseDesc_ids
extern const int *const ORP__PtrBaseDesc_ids[1];

#define ORP__PtrBaseDesc_td compiler__ORP__PtrBaseDesc_td
extern const OBNC_Td ORP__PtrBaseDesc_td;

#define ORP__Module_ compiler__ORP__Module_
void ORP__Module_(void);

#define ORP__Init compiler__ORP__Init
void ORP__Init(void);

#endif
